# Efficiency plotting 

Copied most functionality from Moon's https://github.com/wjdanswjddl/cafpyana/blob/release/numucc_1p0pi/analysis_village/numucc_1p0pi/notebooks/event_selection.ipynb

In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
# print avaialbe memory
import psutil
print(psutil.virtual_memory())

svmem(total=506987724800, available=443870363648, percent=12.4, used=63117361152, free=277471490048, active=88875737088, inactive=130751504384, buffers=7815168, cached=170715398144, shared=88264704, slab=6370865152)

In [3]:
import os
import pandas as pd
import numpy as np
import sys
from pathlib import Path
from os import makedirs, path
from datetime import datetime
import pickle

os.environ['BEARER_TOKEN_FILE'] = f"/tmp/bt_u{os.getuid()}_sbnd"

# local imports
# sys.path.append('../../../')
cwd = Path.cwd().resolve()
# repo_root = next((candidate for candidate in [cwd, *cwd.parents] if (candidate / 'analysis_village').exists()), None)
# if repo_root is None:
#     raise RuntimeError('Could not locate the repository root from the current notebook working directory')
repo_root = Path('/nashome/m/micarrig/sbnd/nueCCNp/cafpyana')
sys.path.append(str(repo_root))
from analysis_village.nueNp0Pi.config.plots import VariableConfig
from analysis_village.nueNp0Pi.config.settings import *
from analysis_village.nueNp0Pi.selections import *
from analysis_village.nueNp0Pi.utils import *
from pyanalib.split_df_helpers import *
from pyanalib.pandas_helpers import *
from pyanalib.covariance import *

import matplotlib.pyplot as plt 
from matplotlib.patches import Patch

plt.style.use(repo_root / 'analysis_village' / 'nueNp0Pi' / 'notebooks' / 'presentation.mplstyle')

# turn off PerformanceWarning 
# triggered by mismatched column levels
import warnings
warnings.filterwarnings('ignore', category=pd.errors.PerformanceWarning)
# turn off RuntimeWarning
warnings.filterwarnings('ignore', category=RuntimeWarning)

os.environ['CAFPYANA_LOG_LEVEL'] = 'DEBUG'
import os

#TODO change this when systematics are implemented (also change naming)
os.environ["NUMUCC_SYST_DISK_ROOT"] = ""

In [7]:
from analysis_village.nueNp0Pi.event_selection import build_event_selection_pipeline
from pyanalib.event_selection_pipeline import EventSelectionPipelineConfig
from analysis_village.nueNp0Pi.config.datasets import PLOTS_BASE

today_str = datetime.now().strftime("%Y%m%d")
syst_tag = ""

# Optional overrides (None -> dated work dir under /exp/sbnd/data/users/$USER/...)
batch_work_base = f"/exp/sbnd/data/users/micarrig/nueNp0Pi/{today_str}"
# batch_work_base = f'/Users/micarrig/Desktop/SBND/cafpyana/plots/'
# batch_plots_dir = path.join(PLOTS_BASE, f"event_selection-{syst_tag}-{today_str}")
batch_plots_dir = path.join(PLOTS_BASE, f"event_selection-debug")

batch_cfg = EventSelectionPipelineConfig(
    work_base=batch_work_base,
    plots_dir=batch_plots_dir,
    max_job_bytes=int(10.0 * 1024**3),  # 1 GiB per job
    mc_univ_syst=(), #("Flux", "G4", "GENIE"),
    skip_existing_batches=False,
    aggregate_only=False,
    skip_aggregate=False,
    save_fig=True,
    show_fig=False,
    # max_files_per_sample=1,  # smoke test: one file per sample
)
pipeline = build_event_selection_pipeline(batch_cfg)

records, jobs, manifest_path = pipeline.discover_jobs()
print(f"Batched workflow: {len(jobs)} job(s)  manifest={manifest_path}")
for j in jobs[:8]:
    print(f"  {j.sample} {j.tag}: {len(j.files)} file(s), {j.total_bytes / (1024**3):.3f} GiB")
if len(jobs) > 8:
    print(f"  ... and {len(jobs) - 8} more")

[event_selection] mc: looking in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_test/*.df
[event_selection] mc: found 6 file(s)
[event_selection] sample=mc  files=6  total=15.90 GiB
[event_selection] 2 job(s) under size budget
  mc batch_0000: 3 file(s), 7.863 GiB
  mc batch_0001: 3 file(s), 8.041 GiB
Batched workflow: 2 job(s)  manifest=/exp/sbnd/data/users/micarrig/nueNp0Pi/20260820/manifest.json
  mc batch_0000: 3 file(s), 7.863 GiB
  mc batch_0001: 3 file(s), 8.041 GiB

### Stacked event-distribution breakdown plots

By default, `build_pipeline()` (in `config/stages.py`) attaches a stacked breakdown plot
for every `EFFICIENCY_VARS` variable, by topology, at the final selection stage -- no
changes needed below to get them. Set the `EVT_BREAKDOWN_*` attributes on the
`config.stages` module before running the pipeline (cell below) to change the
breakdown type, which stage(s) they're attached to, or which variables get one.

In [8]:
batch_result = pipeline.run_full()

save_fig_dir = str(batch_result.plots_dir)
save_fig = batch_cfg.save_fig
show_plot = batch_cfg.show_fig
pot_str = batch_result.pot_str
data_tot_pot = batch_result.data_pot
merged_payload = batch_result.merged_payload

print("Batched workflow complete.")
print("  batches:", batch_result.batches_dir)
print("  plots  :", batch_result.plots_dir)
print("  manifest:", batch_result.manifest_path)
print("  POT    :", pot_str)

# Uncomment to preview PNGs inline (can be slow for many plots):
# pipeline.show_saved_plots(batch_result.plots_dir, max_images=20)

[event_selection] mc: looking in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_test/*.df

[event_selection] mc: found 6 file(s)
[event_selection] sample=mc  files=6  total=15.90 GiB
[event_selection] 2 job(s) under size budget
  mc batch_0000: 3 file(s), 7.863 GiB
  mc batch_0001: 3 file(s), 8.041 GiB
[event_selection] WORK_BASE=/exp/sbnd/data/users/micarrig/nueNp0Pi/20260820
[event_selection] BATCHES_DIR=/exp/sbnd/data/users/micarrig/nueNp0Pi/20260820/batches
[event_selection] sample=mc batch_0000  files=3  size=7.863 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[topology], proton-p[topology], tki-del_Tp[topology], tki-del_alpha[topology], tki-del_phi[topology], tki-del_Tp_lp[topology], tki-del_alpha_lp[topology], tki-del_phi_lp[topology], opening_angle[topology], opening_angle_beam[topology], electron-e-res[topology], electron-dedx[topology], electron-vertex-distance[topology], electron-softmax-score[topology], electron-primary-score[topology], proton-softmax-score[topology], secondary-proton-p[topology], proton-p-res[topology], secondary-proton-p-res[topology], tki-del_alpha_lp-res[topology], tki-del_phi_lp-res[topology], tki-del_Tp_lp-res[topology], tki-del_alpha-res[topology], tki-del_phi-res[topology], tki-del_Tp-res[topology], opening_angle-res[topology], opening_angle_beam-res[topology], num-photons[topology], num-electrons[topology], num-muons[topology], num-pions[topology], num-protons[topology], E_nu[topology])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_test/output_v1_0.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_test/output_v1_0.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=138871 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20209 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12218 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6089 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5120 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4470 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=73 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=44 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=41 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=41 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=34 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=29 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=19 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__topology__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__topology__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__topology__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__topology__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__topology__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__topology__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__topology__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__topology__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__topology__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__topology__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__topology__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__topology__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__topology__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__topology__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__topology__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__topology__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__topology__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__topology__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__topology__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__topology__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__topology__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__topology__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__topology__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__topology__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__topology__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__topology__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__topology__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__topology__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__topology__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__topology__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__topology__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__topology__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__topology__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_test/output_v1_1.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_test/output_v1_1.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=138179 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20024 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12073 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5987 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5125 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4427 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …

[event_selection] done sample=mc batch_0000  n_evt=1535802  pot=1.128e+19
[event_selection] sample=mc batch_0001  files=3  size=8.041 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[topology], proton-p[topology], tki-del_Tp[topology], tki-del_alpha[topology], tki-del_phi[topology], tki-del_Tp_lp[topology], tki-del_alpha_lp[topology], tki-del_phi_lp[topology], opening_angle[topology], opening_angle_beam[topology], electron-e-res[topology], electron-dedx[topology], electron-vertex-distance[topology], electron-softmax-score[topology], electron-primary-score[topology], proton-softmax-score[topology], secondary-proton-p[topology], proton-p-res[topology], secondary-proton-p-res[topology], tki-del_alpha_lp-res[topology], tki-del_phi_lp-res[topology], tki-del_Tp_lp-res[topology], tki-del_alpha-res[topology], tki-del_phi-res[topology], tki-del_Tp-res[topology], opening_angle-res[topology], opening_angle_beam-res[topology], num-photons[topology], num-electrons[topology], num-muons[topology], num-pions[topology], num-protons[topology], E_nu[topology])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_test/output_v1_100.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_test/output_v1_100.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143267 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20696 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12462 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6159 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5249 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4543 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=72 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=42 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=39 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=38 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=32 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=29 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=21 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__topology__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__topology__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__topology__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__topology__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__topology__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__topology__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__topology__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__topology__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__topology__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__topology__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__topology__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__topology__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__topology__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__topology__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__topology__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__topology__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__topology__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__topology__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__topology__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__topology__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__topology__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__topology__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__topology__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__topology__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__topology__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__topology__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__topology__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__topology__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__topology__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__topology__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__topology__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__topology__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__topology__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_test/output_v1_101.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_test/output_v1_101.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=142288 len(trk)=1542790
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20597 len(trk)=1542790
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12462 len(trk)=1542790
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6186 len(trk)=1542790
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5280 len(trk)=1542790
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4545 len(trk)=1542790
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …

[event_selection] done sample=mc batch_0001  n_evt=1570595  pot=1.128e+19
[event_selection] sample=mc wrote 2 batch pickle(s)

[INFO] cafpyana.pyanalib.chunked_selection: aggregating 2 chunk file(s)
[INFO] cafpyana.pyanalib.chunked_selection: merging samples: ['mc']
[INFO] cafpyana.pyanalib.chunked_selection: applied global exposure scales: {'scale_mc': 1.0, 'scale_dirt': 1.0, 'scale_intime': 0.0, 'scale_offbeam': 0.0}

[aggregate] sample=mc -> 2 chunks
[aggregate] sample=data -> 0 chunks
[aggregate] sample=intime -> 0 chunks
[aggregate] sample=offbeam -> 0 chunks
[aggregate] sample=dirt -> 0 chunks
[aggregate] aggregating 2 chunks for sample=mc
[aggregate] exposure totals: data_pot=0.000e+00 bnb_gates=0.000e+00 mc_pot=2.256e+19 dirt_pot=0.000e+00 intime_gates=0.000e+00 offbeam_gates=0.000e+00
[aggregate] applied global scales: {'scale_mc': 1.0, 'scale_dirt': 1.0, 'scale_intime': 0.0, 'scale_offbeam': 0.0}
[aggregate] data_pot (legend)=2.256e+19 -> POT label=2.26$\times 10^{19}$
[aggregate] systematics disk root: None

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[topology], proton-p[topology], tki-del_Tp[topology], tki-del_alpha[topology], tki-del_phi[topology], tki-del_Tp_lp[topology], tki-del_alpha_lp[topology], tki-del_phi_lp[topology], opening_angle[topology], opening_angle_beam[topology], electron-e-res[topology], electron-dedx[topology], electron-vertex-distance[topology], electron-softmax-score[topology], electron-primary-score[topology], proton-softmax-score[topology], secondary-proton-p[topology], proton-p-res[topology], secondary-proton-p-res[topology], tki-del_alpha_lp-res[topology], tki-del_phi_lp-res[topology], tki-del_Tp_lp-res[topology], tki-del_alpha-res[topology], tki-del_phi-res[topology], tki-del_Tp-res[topology], opening_angle-res[topology], opening_angle_beam-res[topology], num-photons[topology], num-electrons[topology], num-muons[topology], num-pions[topology], num-protons[topology], E_nu[topology])  flags=eff,breakdown

[aggregate] overlay plots without syst covariance (34 plots, 34 distinct var_save_name): E_nu, electron-dedx, electron-e, electron-e-res, electron-primary-score, electron-softmax-score, electron-vertex-distance, num-electrons, num-muons, num-photons, num-pions, num-protons, opening_angle, opening_angle-res, opening_angle_beam, opening_angle_beam-res, particle_ke, proton-p, proton-p-res, proton-softmax-score, secondary-proton-p, secondary-proton-p-res, tki-del_Tp, tki-del_Tp-res, tki-del_Tp_lp, tki-del_Tp_lp-res, tki-del_alpha, tki-del_alpha-res, tki-del_alpha_lp, tki-del_alpha_lp-res, tki-del_phi, tki-del_phi-res, tki-del_phi_lp, tki-del_phi_lp-res

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[topology], proton-p[topology], tki-del_Tp[topology], tki-del_alpha[topology], tki-del_phi[topology], tki-del_Tp_lp[topology], tki-del_alpha_lp[topology], tki-del_phi_lp[topology], opening_angle[topology], opening_angle_beam[topology], electron-e-res[topology], electron-dedx[topology], electron-vertex-distance[topology], electron-softmax-score[topology], electron-primary-score[topology], proton-softmax-score[topology], secondary-proton-p[topology], proton-p-res[topology], secondary-proton-p-res[topology], tki-del_alpha_lp-res[topology], tki-del_phi_lp-res[topology], tki-del_Tp_lp-res[topology], tki-del_alpha-res[topology], tki-del_phi-res[topology], tki-del_Tp-res[topology], opening_angle-res[topology], opening_angle_beam-res[topology], num-photons[topology], num-electrons[topology], num-muons[topology], num-pions[topology], num-protons[topology], E_nu[topology])  flags=eff,breakdown

[aggregate] final selection purity: 86.29% (weighted)  86.29% (raw counts, notebook-style)
[aggregate] wrote /nashome/m/micarrig/sbnd/nueCCNp/plots/event_selection-debug/pkl/eff_dict.pkl
[aggregate] wrote /nashome/m/micarrig/sbnd/nueCCNp/plots/event_selection-debug/pkl/merged_histdata.pkl
[event_selection] DONE plots -> /nashome/m/micarrig/sbnd/nueCCNp/plots/event_selection-debug
Batched workflow complete.
  batches: /exp/sbnd/data/users/micarrig/nueNp0Pi/20260820/batches
  plots  : /nashome/m/micarrig/sbnd/nueCCNp/plots/event_selection-debug
  manifest: /exp/sbnd/data/users/micarrig/nueNp0Pi/20260820/manifest.json
  POT    : 2.26$\times 10^{19}$

In [150]:
import analysis_village.nueNp0Pi.config.stages as stages_mod

# Uncomment/edit any of these before running the pipeline below. Defaults shown.
stages_mod.EVT_BREAKDOWN_TYPE = "genie"           # "topology" | "genie" | "pdg"
stages_mod.EVT_BREAKDOWN_DIR_NAME = f"selection_{stages_mod.EVT_BREAKDOWN_TYPE}"
# stages_mod.EVT_BREAKDOWN_STAGE_KEYS = None            # None -> final stage only; or e.g. ["no_photons", "electron_dedx"]
# stages_mod.EVT_BREAKDOWN_VARS = stages_mod.EFFICIENCY_VARS  # or e.g. [VariableConfig.neutrino_energy()]
# stages_mod.EVT_BREAKDOWN_VARS = []                    # uncomment to disable these plots entirely

# Output subdirectory for these plots (under the plots dir), default "selection". Set this
# alongside EVT_BREAKDOWN_TYPE if you want to run more than one breakdown_type (e.g. once as
# "topology", once as "genie") without the later run's selection_<var>.png files
# overwriting the earlier run's -- e.g.:
# stages_mod.EVT_BREAKDOWN_DIR_NAME = f"selection_{stages_mod.EVT_BREAKDOWN_TYPE}"

In [151]:
batch_result = pipeline.run_full()

save_fig_dir = str(batch_result.plots_dir)
save_fig = batch_cfg.save_fig
show_plot = batch_cfg.show_fig
pot_str = batch_result.pot_str
data_tot_pot = batch_result.data_pot
merged_payload = batch_result.merged_payload

print("Batched workflow complete.")
print("  batches:", batch_result.batches_dir)
print("  plots  :", batch_result.plots_dir)
print("  manifest:", batch_result.manifest_path)
print("  POT    :", pot_str)

# Uncomment to preview PNGs inline (can be slow for many plots):
# pipeline.show_saved_plots(batch_result.plots_dir, max_images=20)

[event_selection] mc: looking in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/*.df
[event_selection] mc: found 160 file(s)
[event_selection] sample=mc  files=160  total=426.49 GiB
[event_selection] 53 job(s) under size budget
  mc batch_0000: 3 file(s), 7.863 GiB
  mc batch_0001: 3 file(s), 8.041 GiB
  mc batch_0002: 3 file(s), 8.054 GiB
  mc batch_0003: 4 file(s), 9.650 GiB
  mc batch_0004: 3 file(s), 7.987 GiB
  mc batch_0005: 3 file(s), 7.971 GiB
  mc batch_0006: 3 file(s), 7.952 GiB
  mc batch_0007: 4 file(s), 9.630 GiB
  mc batch_0008: 3 file(s), 7.450 GiB
  mc batch_0009: 3 file(s), 7.936 GiB
  mc batch_0010: 3 file(s), 8.067 GiB
  mc batch_0011: 3 file(s), 8.101 GiB
  ... and 41 more
[event_selection] WORK_BASE=/exp/sbnd/data/users/micarrig/nueNp0Pi/20260820
[event_selection] BATCHES_DIR=/exp/sbnd/data/users/micarrig/nueNp0Pi/20260820/batches
[event_selection] sample=mc batch_0000  files=3  size=7.863 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_0.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_0.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=138871 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20209 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12218 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6089 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5120 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4470 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=73 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=44 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=41 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=41 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=34 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=29 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=19 len(trk)=1505558
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_1.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_1.df: ['evt', 'trk', 'hdr', 'mcnu']

[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=138179 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20024 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12073 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5987 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5125 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4427 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=68 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=44 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=33 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=33 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=29 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=29 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=21 len(trk)=1490936
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_10.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_10.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143139 len(trk)=1557577
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20782 len(trk)=1557577
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12502 len(trk)=1557577
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6242 len(trk)=1557577
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5277 len(trk)=1557577
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4563 len(trk)=1557577
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=74 len(trk)=1557577
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=41 len(trk)=1557577
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=34 len(trk)=1557577
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=34 len(trk)=1557577
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=28 len(trk)=1557577
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=24 len(trk)=1557577
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …

[event_selection] done sample=mc batch_0000  n_evt=1535802  pot=1.128e+19
[event_selection] sample=mc batch_0001  files=3  size=8.041 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_100.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_100.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143267 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20696 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12462 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6159 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5249 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4543 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=72 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=42 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=39 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=38 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=32 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=29 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=21 len(trk)=1548532
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_101.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_101.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=142288 len(trk)=1542790
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20597 len(trk)=1542790
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12462 len(trk)=1542790
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6186 len(trk)=1542790
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5280 len(trk)=1542790
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4545 len(trk)=1542790
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=71 len(trk)=1542790
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0001  n_evt=1570595  pot=1.128e+19
[event_selection] sample=mc batch_0002  files=3  size=8.054 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_103.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_103.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143256 len(trk)=1557683
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20864 len(trk)=1557683
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12595 len(trk)=1557683
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6181 len(trk)=1557683
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5334 len(trk)=1557683
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4614 len(trk)=1557683
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=71 len(trk)=1557683
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=39 len(trk)=1557683
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=31 len(trk)=1557683
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=31 len(trk)=1557683
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=26 len(trk)=1557683
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=25 len(trk)=1557683
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=15 len(trk)=1557683
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_104.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_104.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143385 len(trk)=1550432
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20609 len(trk)=1550432
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12396 len(trk)=1550432
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6087 len(trk)=1550432
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5177 len(trk)=1550432
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4471 len(trk)=1550432
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=71 len(trk)=1550432
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0002  n_evt=1572952  pot=1.127e+19
[event_selection] sample=mc batch_0003  files=4  size=9.650 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_106.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_106.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=142857 len(trk)=1540565
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20668 len(trk)=1540565
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12542 len(trk)=1540565
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6205 len(trk)=1540565
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5310 len(trk)=1540565
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4585 len(trk)=1540565
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=59 len(trk)=1540565
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=31 len(trk)=1540565
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=27 len(trk)=1540565
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=27 len(trk)=1540565
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=25 len(trk)=1540565
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=24 len(trk)=1540565
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=16 len(trk)=1540565
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_107.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_107.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143920 len(trk)=1563102
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20798 len(trk)=1563102
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12611 len(trk)=1563102
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6194 len(trk)=1563102
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5277 len(trk)=1563102
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4569 len(trk)=1563102
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=56 len(trk)=1563102
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0003  n_evt=1885188  pot=1.354e+19
[event_selection] sample=mc batch_0004  files=3  size=7.987 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_11.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_11.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143323 len(trk)=1542987
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20708 len(trk)=1542987
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12536 len(trk)=1542987
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6241 len(trk)=1542987
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5319 len(trk)=1542987
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4580 len(trk)=1542987
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=67 len(trk)=1542987
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=39 len(trk)=1542987
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=35 len(trk)=1542987
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=35 len(trk)=1542987
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=29 len(trk)=1542987
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=28 len(trk)=1542987
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=19 len(trk)=1542987
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_110.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_110.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=140297 len(trk)=1514093
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20412 len(trk)=1514093
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12302 len(trk)=1514093
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6142 len(trk)=1514093
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5184 len(trk)=1514093
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4478 len(trk)=1514093
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=53 len(trk)=1514093
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0004  n_evt=1560900  pot=1.128e+19
[event_selection] sample=mc batch_0005  files=3  size=7.971 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_112.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_112.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=142684 len(trk)=1545666
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20571 len(trk)=1545666
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12358 len(trk)=1545666
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6067 len(trk)=1545666
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5222 len(trk)=1545666
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4583 len(trk)=1545666
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=55 len(trk)=1545666
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=31 len(trk)=1545666
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=27 len(trk)=1545666
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=27 len(trk)=1545666
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=24 len(trk)=1545666
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=22 len(trk)=1545666
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=16 len(trk)=1545666
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_113.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_113.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=140537 len(trk)=1528797
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20547 len(trk)=1528797
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12363 len(trk)=1528797
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6165 len(trk)=1528797
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5243 len(trk)=1528797
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4514 len(trk)=1528797
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=67 len(trk)=1528797
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0005  n_evt=1556293  pot=1.129e+19
[event_selection] sample=mc batch_0006  files=3  size=7.952 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_115.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_115.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143911 len(trk)=1560919
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20794 len(trk)=1560919
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12457 len(trk)=1560919
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6178 len(trk)=1560919
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5209 len(trk)=1560919
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4512 len(trk)=1560919
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=63 len(trk)=1560919
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=36 len(trk)=1560919
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=34 len(trk)=1560919
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=34 len(trk)=1560919
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=27 len(trk)=1560919
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=25 len(trk)=1560919
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=22 len(trk)=1560919
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_116.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_116.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=141699 len(trk)=1537434
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20641 len(trk)=1537434
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12255 len(trk)=1537434
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5989 len(trk)=1537434
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5122 len(trk)=1537434
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4439 len(trk)=1537434
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=67 len(trk)=1537434
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0006  n_evt=1553325  pot=1.129e+19
[event_selection] sample=mc batch_0007  files=4  size=9.630 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[WARNING] cafpyana.pyanalib.split_df_helpers_new: [get_n_split] /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_118.df: split table says n_split=2 but only 1 'evt_*' keys exist; using 1
[WARNING] cafpyana.pyanalib.split_df_helpers_new: [get_n_split] /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_118.df: split table says n_split=2 but only 1 'evt_*' keys exist; using 1
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 1 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_118.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_118.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=113547 len(trk)=1232952
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=16627 len(trk)=1232952
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=10050 len(trk)=1232952
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4987 len(trk)=1232952
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4238 len(trk)=1232952
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=3680 len(trk)=1232952
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=55 len(trk)=1232952
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=35 len(trk)=1232952
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=32 len(trk)=1232952
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=32 len(trk)=1232952
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=26 len(trk)=1232952
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=24 len(trk)=1232952
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=19 len(trk)=1232952
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_119.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_119.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=115795 len(trk)=1265838
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=16865 len(trk)=1265838
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=10121 len(trk)=1265838
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4911 len(trk)=1265838
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4215 len(trk)=1265838
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=3652 len(trk)=1265838
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished

[event_selection] done sample=mc batch_0007  n_evt=1879741  pot=1.354e+19
[event_selection] sample=mc batch_0008  files=3  size=7.450 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_121.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_121.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=141034 len(trk)=1528040
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20417 len(trk)=1528040
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12344 len(trk)=1528040
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6009 len(trk)=1528040
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5146 len(trk)=1528040
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4461 len(trk)=1528040
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=68 len(trk)=1528040
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=31 len(trk)=1528040
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=27 len(trk)=1528040
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=27 len(trk)=1528040
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=25 len(trk)=1528040
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=23 len(trk)=1528040
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=17 len(trk)=1528040
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_122.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_122.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=141990 len(trk)=1532313
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20429 len(trk)=1532313
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12322 len(trk)=1532313
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6022 len(trk)=1532313
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5131 len(trk)=1532313
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4455 len(trk)=1532313
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=64 len(trk)=1532313
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0008  n_evt=1454724  pot=1.053e+19
[event_selection] sample=mc batch_0009  files=3  size=7.936 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_124.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_124.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=141580 len(trk)=1534014
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20425 len(trk)=1534014
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12346 len(trk)=1534014
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6059 len(trk)=1534014
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5153 len(trk)=1534014
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4471 len(trk)=1534014
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=66 len(trk)=1534014
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=36 len(trk)=1534014
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=32 len(trk)=1534014
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=32 len(trk)=1534014
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=26 len(trk)=1534014
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=23 len(trk)=1534014
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=21 len(trk)=1534014
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_125.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_125.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=141715 len(trk)=1522741
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20446 len(trk)=1522741
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12345 len(trk)=1522741
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6086 len(trk)=1522741
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5135 len(trk)=1522741
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4435 len(trk)=1522741
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=64 len(trk)=1522741
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0009  n_evt=1550553  pot=1.128e+19
[event_selection] sample=mc batch_0010  files=3  size=8.067 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_127.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_127.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=144439 len(trk)=1563349
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20881 len(trk)=1563349
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12603 len(trk)=1563349
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6139 len(trk)=1563349
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5260 len(trk)=1563349
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4576 len(trk)=1563349
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=58 len(trk)=1563349
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=37 len(trk)=1563349
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=34 len(trk)=1563349
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=32 len(trk)=1563349
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=31 len(trk)=1563349
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=29 len(trk)=1563349
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=24 len(trk)=1563349
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_128.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_128.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143168 len(trk)=1552490
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20647 len(trk)=1552490
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12370 len(trk)=1552490
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6026 len(trk)=1552490
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5129 len(trk)=1552490
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4458 len(trk)=1552490
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=67 len(trk)=1552490
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0010  n_evt=1574424  pot=1.129e+19
[event_selection] sample=mc batch_0011  files=3  size=8.101 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_13.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_13.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=145051 len(trk)=1571523
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20966 len(trk)=1571523
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12568 len(trk)=1571523
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6174 len(trk)=1571523
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5328 len(trk)=1571523
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4624 len(trk)=1571523
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=86 len(trk)=1571523
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=50 len(trk)=1571523
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=42 len(trk)=1571523
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=40 len(trk)=1571523
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=35 len(trk)=1571523
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=31 len(trk)=1571523
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=17 len(trk)=1571523
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_130.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_130.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=144575 len(trk)=1557575
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20816 len(trk)=1557575
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12530 len(trk)=1557575
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6228 len(trk)=1557575
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5314 len(trk)=1557575
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4588 len(trk)=1557575
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=54 len(trk)=1557575
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0011  n_evt=1581985  pot=1.130e+19
[event_selection] sample=mc batch_0012  files=3  size=8.002 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_132.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_132.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=142756 len(trk)=1545821
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20643 len(trk)=1545821
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12605 len(trk)=1545821
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6293 len(trk)=1545821
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5345 len(trk)=1545821
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4634 len(trk)=1545821
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=59 len(trk)=1545821
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=44 len(trk)=1545821
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=39 len(trk)=1545821
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=39 len(trk)=1545821
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=34 len(trk)=1545821
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=28 len(trk)=1545821
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=22 len(trk)=1545821
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_133.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_133.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=140629 len(trk)=1523571
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20391 len(trk)=1523571
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12213 len(trk)=1523571
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6093 len(trk)=1523571
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5199 len(trk)=1523571
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4487 len(trk)=1523571
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=65 len(trk)=1523571
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0012  n_evt=1563085  pot=1.130e+19
[event_selection] sample=mc batch_0013  files=3  size=8.129 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_135.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_135.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=144255 len(trk)=1566209
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20787 len(trk)=1566209
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12555 len(trk)=1566209
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6227 len(trk)=1566209
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5366 len(trk)=1566209
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4631 len(trk)=1566209
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=68 len(trk)=1566209
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=35 len(trk)=1566209
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=29 len(trk)=1566209
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=29 len(trk)=1566209
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=25 len(trk)=1566209
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=23 len(trk)=1566209
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=17 len(trk)=1566209
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_136.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_136.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=145236 len(trk)=1571446
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=21001 len(trk)=1571446
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12630 len(trk)=1571446
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6321 len(trk)=1571446
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5364 len(trk)=1571446
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4686 len(trk)=1571446
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=77 len(trk)=1571446
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0013  n_evt=1586059  pot=1.128e+19
[event_selection] sample=mc batch_0014  files=3  size=8.081 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_138.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_138.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=144260 len(trk)=1558762
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20748 len(trk)=1558762
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12482 len(trk)=1558762
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6130 len(trk)=1558762
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5245 len(trk)=1558762
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4566 len(trk)=1558762
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=75 len(trk)=1558762
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=52 len(trk)=1558762
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=47 len(trk)=1558762
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=47 len(trk)=1558762
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=40 len(trk)=1558762
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=39 len(trk)=1558762
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=31 len(trk)=1558762
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_139.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_139.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=144090 len(trk)=1567183
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20729 len(trk)=1567183
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12477 len(trk)=1567183
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6203 len(trk)=1567183
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5271 len(trk)=1567183
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4552 len(trk)=1567183
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=69 len(trk)=1567183
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0014  n_evt=1578457  pot=1.129e+19
[event_selection] sample=mc batch_0015  files=3  size=8.161 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_140.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_140.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=146754 len(trk)=1589336
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=21037 len(trk)=1589336
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12705 len(trk)=1589336
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6274 len(trk)=1589336
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5338 len(trk)=1589336
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4617 len(trk)=1589336
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=64 len(trk)=1589336
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=37 len(trk)=1589336
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=30 len(trk)=1589336
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=30 len(trk)=1589336
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=29 len(trk)=1589336
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=28 len(trk)=1589336
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=25 len(trk)=1589336
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_141.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_141.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=144669 len(trk)=1579412
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20851 len(trk)=1579412
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12517 len(trk)=1579412
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6098 len(trk)=1579412
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5164 len(trk)=1579412
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4430 len(trk)=1579412
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=69 len(trk)=1579412
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0015  n_evt=1593094  pot=1.129e+19
[event_selection] sample=mc batch_0016  files=3  size=8.117 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_143.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_143.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=144816 len(trk)=1571590
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20850 len(trk)=1571590
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12534 len(trk)=1571590
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6130 len(trk)=1571590
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5289 len(trk)=1571590
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4573 len(trk)=1571590
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=68 len(trk)=1571590
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=43 len(trk)=1571590
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=42 len(trk)=1571590
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=42 len(trk)=1571590
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=39 len(trk)=1571590
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=37 len(trk)=1571590
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=26 len(trk)=1571590
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_144.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_144.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143389 len(trk)=1558228
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20838 len(trk)=1558228
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12603 len(trk)=1558228
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6168 len(trk)=1558228
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5242 len(trk)=1558228
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4524 len(trk)=1558228
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=61 len(trk)=1558228
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0016  n_evt=1584519  pot=1.128e+19
[event_selection] sample=mc batch_0017  files=3  size=8.148 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_146.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_146.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=144369 len(trk)=1564950
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=21032 len(trk)=1564950
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12760 len(trk)=1564950
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6267 len(trk)=1564950
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5312 len(trk)=1564950
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4575 len(trk)=1564950
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=72 len(trk)=1564950
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=45 len(trk)=1564950
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=43 len(trk)=1564950
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=43 len(trk)=1564950
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=36 len(trk)=1564950
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=34 len(trk)=1564950
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=25 len(trk)=1564950
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_147.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_147.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=146033 len(trk)=1578007
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=21026 len(trk)=1578007
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12522 len(trk)=1578007
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6154 len(trk)=1578007
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5227 len(trk)=1578007
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4474 len(trk)=1578007
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=59 len(trk)=1578007
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0017  n_evt=1591496  pot=1.128e+19
[event_selection] sample=mc batch_0018  files=3  size=8.070 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_149.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_149.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=144528 len(trk)=1561079
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20725 len(trk)=1561079
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12422 len(trk)=1561079
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6152 len(trk)=1561079
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5274 len(trk)=1561079
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4591 len(trk)=1561079
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=66 len(trk)=1561079
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=37 len(trk)=1561079
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=35 len(trk)=1561079
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=35 len(trk)=1561079
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=32 len(trk)=1561079
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=28 len(trk)=1561079
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=22 len(trk)=1561079
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_15.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_15.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=142658 len(trk)=1549753
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20498 len(trk)=1549753
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12293 len(trk)=1549753
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5986 len(trk)=1549753
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5079 len(trk)=1549753
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4390 len(trk)=1549753
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=66 len(trk)=1549753
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0018  n_evt=1576542  pot=1.131e+19
[event_selection] sample=mc batch_0019  files=3  size=8.049 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_151.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_151.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143331 len(trk)=1554695
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20611 len(trk)=1554695
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12537 len(trk)=1554695
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6126 len(trk)=1554695
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5258 len(trk)=1554695
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4546 len(trk)=1554695
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=59 len(trk)=1554695
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=38 len(trk)=1554695
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=32 len(trk)=1554695
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=32 len(trk)=1554695
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=25 len(trk)=1554695
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20 len(trk)=1554695
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=16 len(trk)=1554695
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_152.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_152.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=144369 len(trk)=1561483
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20835 len(trk)=1561483
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12674 len(trk)=1561483
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6168 len(trk)=1561483
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5280 len(trk)=1561483
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4571 len(trk)=1561483
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=71 len(trk)=1561483
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0019  n_evt=1571528  pot=1.128e+19
[event_selection] sample=mc batch_0020  files=3  size=8.088 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_154.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_154.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143421 len(trk)=1558931
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20647 len(trk)=1558931
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12472 len(trk)=1558931
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6206 len(trk)=1558931
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5273 len(trk)=1558931
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4553 len(trk)=1558931
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=80 len(trk)=1558931
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=34 len(trk)=1558931
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=30 len(trk)=1558931
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=30 len(trk)=1558931
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=28 len(trk)=1558931
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=26 len(trk)=1558931
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=18 len(trk)=1558931
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_155.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_155.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143612 len(trk)=1557451
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20722 len(trk)=1557451
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12443 len(trk)=1557451
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6158 len(trk)=1557451
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5257 len(trk)=1557451
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4565 len(trk)=1557451
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=57 len(trk)=1557451
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0020  n_evt=1579541  pot=1.128e+19
[event_selection] sample=mc batch_0021  files=4  size=9.777 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_157.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_157.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=144689 len(trk)=1568219
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20888 len(trk)=1568219
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12621 len(trk)=1568219
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6336 len(trk)=1568219
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5440 len(trk)=1568219
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4721 len(trk)=1568219
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=73 len(trk)=1568219
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=48 len(trk)=1568219
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=41 len(trk)=1568219
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=41 len(trk)=1568219
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=38 len(trk)=1568219
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=36 len(trk)=1568219
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=27 len(trk)=1568219
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_158.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_158.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=118401 len(trk)=1283052
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=17209 len(trk)=1283052
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=10337 len(trk)=1283052
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5077 len(trk)=1283052
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4352 len(trk)=1283052
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=3829 len(trk)=1283052
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=64 len(trk)=1283052
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0021  n_evt=1909473  pot=1.362e+19
[event_selection] sample=mc batch_0022  files=3  size=8.127 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_17.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_17.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=146753 len(trk)=1587856
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=21011 len(trk)=1587856
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12683 len(trk)=1587856
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6278 len(trk)=1587856
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5358 len(trk)=1587856
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4656 len(trk)=1587856
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=64 len(trk)=1587856
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=42 len(trk)=1587856
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=38 len(trk)=1587856
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=36 len(trk)=1587856
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=31 len(trk)=1587856
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=27 len(trk)=1587856
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=18 len(trk)=1587856
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_18.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_18.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143736 len(trk)=1559390
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20752 len(trk)=1559390
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12488 len(trk)=1559390
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6181 len(trk)=1559390
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5234 len(trk)=1559390
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4528 len(trk)=1559390
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=68 len(trk)=1559390
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0022  n_evt=1586447  pot=1.129e+19
[event_selection] sample=mc batch_0023  files=3  size=8.099 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_2.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_2.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=144672 len(trk)=1571065
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20822 len(trk)=1571065
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12616 len(trk)=1571065
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6220 len(trk)=1571065
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5302 len(trk)=1571065
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4588 len(trk)=1571065
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=71 len(trk)=1571065
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=39 len(trk)=1571065
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=34 len(trk)=1571065
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=34 len(trk)=1571065
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=24 len(trk)=1571065
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=22 len(trk)=1571065
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=13 len(trk)=1571065
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_20.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_20.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=142958 len(trk)=1554837
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20655 len(trk)=1554837
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12512 len(trk)=1554837
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6059 len(trk)=1554837
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5172 len(trk)=1554837
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4495 len(trk)=1554837
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=72 len(trk)=1554837
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0023  n_evt=1580618  pot=1.129e+19
[event_selection] sample=mc batch_0024  files=3  size=8.118 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_22.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_22.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=144774 len(trk)=1570211
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20961 len(trk)=1570211
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12601 len(trk)=1570211
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6265 len(trk)=1570211
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5339 len(trk)=1570211
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4665 len(trk)=1570211
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=75 len(trk)=1570211
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=42 len(trk)=1570211
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=37 len(trk)=1570211
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=36 len(trk)=1570211
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=35 len(trk)=1570211
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=31 len(trk)=1570211
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=26 len(trk)=1570211
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_23.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_23.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=144509 len(trk)=1554603
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20877 len(trk)=1554603
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12484 len(trk)=1554603
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6148 len(trk)=1554603
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5267 len(trk)=1554603
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4576 len(trk)=1554603
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=67 len(trk)=1554603
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0024  n_evt=1586338  pot=1.128e+19
[event_selection] sample=mc batch_0025  files=3  size=8.036 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_25.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_25.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=144299 len(trk)=1571119
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20730 len(trk)=1571119
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12564 len(trk)=1571119
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6117 len(trk)=1571119
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5210 len(trk)=1571119
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4500 len(trk)=1571119
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=62 len(trk)=1571119
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=36 len(trk)=1571119
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=31 len(trk)=1571119
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=31 len(trk)=1571119
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=28 len(trk)=1571119
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=26 len(trk)=1571119
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20 len(trk)=1571119
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_26.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_26.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143117 len(trk)=1553676
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20676 len(trk)=1553676
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12481 len(trk)=1553676
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6222 len(trk)=1553676
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5280 len(trk)=1553676
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4593 len(trk)=1553676
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=77 len(trk)=1553676
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0025  n_evt=1569337  pot=1.128e+19
[event_selection] sample=mc batch_0026  files=3  size=8.056 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_28.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_28.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=142535 len(trk)=1541531
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20640 len(trk)=1541531
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12398 len(trk)=1541531
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5996 len(trk)=1541531
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5133 len(trk)=1541531
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4459 len(trk)=1541531
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=69 len(trk)=1541531
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=40 len(trk)=1541531
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=33 len(trk)=1541531
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=33 len(trk)=1541531
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=29 len(trk)=1541531
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=25 len(trk)=1541531
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20 len(trk)=1541531
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_29.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_29.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143479 len(trk)=1557607
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20657 len(trk)=1557607
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12530 len(trk)=1557607
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6126 len(trk)=1557607
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5219 len(trk)=1557607
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4535 len(trk)=1557607
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=75 len(trk)=1557607
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0026  n_evt=1573554  pot=1.128e+19
[event_selection] sample=mc batch_0027  files=3  size=8.001 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_30.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_30.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143500 len(trk)=1554285
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20718 len(trk)=1554285
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12454 len(trk)=1554285
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6111 len(trk)=1554285
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5231 len(trk)=1554285
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4532 len(trk)=1554285
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=72 len(trk)=1554285
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=42 len(trk)=1554285
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=33 len(trk)=1554285
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=33 len(trk)=1554285
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=27 len(trk)=1554285
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=23 len(trk)=1554285
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=18 len(trk)=1554285
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_31.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_31.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=141814 len(trk)=1535549
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20501 len(trk)=1535549
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12188 len(trk)=1535549
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5967 len(trk)=1535549
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5084 len(trk)=1535549
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4389 len(trk)=1535549
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=73 len(trk)=1535549
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0027  n_evt=1562847  pot=1.129e+19
[event_selection] sample=mc batch_0028  files=3  size=8.193 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_33.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_33.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=145313 len(trk)=1569034
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=21131 len(trk)=1569034
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12589 len(trk)=1569034
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6149 len(trk)=1569034
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5240 len(trk)=1569034
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4526 len(trk)=1569034
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=61 len(trk)=1569034
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=38 len(trk)=1569034
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=34 len(trk)=1569034
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=32 len(trk)=1569034
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=26 len(trk)=1569034
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=23 len(trk)=1569034
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=15 len(trk)=1569034
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_34.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_34.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=146529 len(trk)=1593670
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=21031 len(trk)=1593670
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12727 len(trk)=1593670
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6360 len(trk)=1593670
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5449 len(trk)=1593670
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4774 len(trk)=1593670
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=68 len(trk)=1593670
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0028  n_evt=1599820  pot=1.127e+19
[event_selection] sample=mc batch_0029  files=3  size=8.149 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_36.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_36.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=145815 len(trk)=1582760
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20890 len(trk)=1582760
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12477 len(trk)=1582760
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6065 len(trk)=1582760
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5124 len(trk)=1582760
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4458 len(trk)=1582760
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=51 len(trk)=1582760
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=26 len(trk)=1582760
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=22 len(trk)=1582760
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=22 len(trk)=1582760
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20 len(trk)=1582760
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=17 len(trk)=1582760
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=14 len(trk)=1582760
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_37.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_37.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=144081 len(trk)=1567424
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20820 len(trk)=1567424
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12589 len(trk)=1567424
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6289 len(trk)=1567424
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5361 len(trk)=1567424
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4625 len(trk)=1567424
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=73 len(trk)=1567424
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0029  n_evt=1591160  pot=1.130e+19
[event_selection] sample=mc batch_0030  files=3  size=8.047 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_39.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_39.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143012 len(trk)=1548210
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20752 len(trk)=1548210
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12438 len(trk)=1548210
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6134 len(trk)=1548210
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5244 len(trk)=1548210
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4585 len(trk)=1548210
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=55 len(trk)=1548210
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=28 len(trk)=1548210
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=26 len(trk)=1548210
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=25 len(trk)=1548210
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=22 len(trk)=1548210
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=21 len(trk)=1548210
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=14 len(trk)=1548210
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_4.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_4.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=143069 len(trk)=1553167
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20641 len(trk)=1553167
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12368 len(trk)=1553167
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6085 len(trk)=1553167
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5158 len(trk)=1553167
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4446 len(trk)=1553167
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=75 len(trk)=1553167
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0030  n_evt=1570994  pot=1.128e+19
[event_selection] sample=mc batch_0031  files=3  size=8.084 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_41.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_41.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=144572 len(trk)=1560430
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20739 len(trk)=1560430
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12547 len(trk)=1560430
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6192 len(trk)=1560430
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5289 len(trk)=1560430
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4573 len(trk)=1560430
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=71 len(trk)=1560430
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=44 len(trk)=1560430
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=37 len(trk)=1560430
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=37 len(trk)=1560430
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=30 len(trk)=1560430
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=28 len(trk)=1560430
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=22 len(trk)=1560430
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_42.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_42.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=144646 len(trk)=1565594
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20882 len(trk)=1565594
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12534 len(trk)=1565594
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6089 len(trk)=1565594
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5184 len(trk)=1565594
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4459 len(trk)=1565594
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=63 len(trk)=1565594
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …

[event_selection] done sample=mc batch_0031  n_evt=1578189  pot=1.127e+19
[event_selection] sample=mc batch_0032  files=3  size=8.137 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=33 (electron-e[genie], proton-p[genie], tki-del_Tp[genie], tki-del_alpha[genie], tki-del_phi[genie], tki-del_Tp_lp[genie], tki-del_alpha_lp[genie], tki-del_phi_lp[genie], opening_angle[genie], opening_angle_beam[genie], electron-e-res[genie], electron-dedx[genie], electron-vertex-distance[genie], electron-softmax-score[genie], electron-primary-score[genie], proton-softmax-score[genie], secondary-proton-p[genie], proton-p-res[genie], secondary-proton-p-res[genie], tki-del_alpha_lp-res[genie], tki-del_phi_lp-res[genie], tki-del_Tp_lp-res[genie], tki-del_alpha-res[genie], tki-del_phi-res[genie], tki-del_Tp-res[genie], opening_angle-res[genie], opening_angle_beam-res[genie], num-photons[genie], num-electrons[genie], num-muons[genie], num-pions[genie], num-protons[genie], E_nu[genie])  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_44.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_44.df: ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] precomputed N-1 cut masks for stages: ['electron_dedx', 'electron_primary', 'electron_softmax', 'electron_vertex_distance', 'good_electron', 'good_proton', 'is_contained', 'is_fiducial', 'is_flash_matched', 'no_muons', 'no_photons', 'no_pions', 'proton_softmax']
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='allreco' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='allreco' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_fiducial' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=145177 len(trk)=1576421
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_fiducial' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_flash_matched' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=20821 len(trk)=1576421
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_flash_matched' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='is_contained' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=12642 len(trk)=1576421
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='is_contained' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_muons' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=6137 len(trk)=1576421
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_muons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_pions' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=5187 len(trk)=1576421
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_pions' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='no_photons' plots=1 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=4487 len(trk)=1576421
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/1 → no_photons__pdg__particle_ke
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='no_photons' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_electron' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=73 len(trk)=1576421
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_electron' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='good_proton' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=45 len(trk)=1576421
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='good_proton' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=41 len(trk)=1576421
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_primary' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=40 len(trk)=1576421
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_primary' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='proton_softmax' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=31 len(trk)=1576421
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='proton_softmax' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_vertex_distance' plots=0 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=26 len(trk)=1576421
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_vertex_distance' finished
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] >>> stage='electron_dedx' plots=33 breakdown=True eff=True
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     executing cut '_cut' …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     after cut: len(evt)=21 len(trk)=1576421
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 1/33 → electron_dedx__genie__electron-e
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 2/33 → electron_dedx__genie__proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 3/33 → electron_dedx__genie__tki-del_Tp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 4/33 → electron_dedx__genie__tki-del_alpha
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 5/33 → electron_dedx__genie__tki-del_phi
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 6/33 → electron_dedx__genie__tki-del_Tp_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 7/33 → electron_dedx__genie__tki-del_alpha_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 8/33 → electron_dedx__genie__tki-del_phi_lp
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 9/33 → electron_dedx__genie__opening_angle
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 10/33 → electron_dedx__genie__opening_angle_beam
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 11/33 → electron_dedx__genie__electron-e-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 12/33 → electron_dedx__genie__electron-dedx
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 13/33 → electron_dedx__genie__electron-vertex-distance
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 14/33 → electron_dedx__genie__electron-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 15/33 → electron_dedx__genie__electron-primary-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 16/33 → electron_dedx__genie__proton-softmax-score
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 17/33 → electron_dedx__genie__secondary-proton-p
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 18/33 → electron_dedx__genie__proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 19/33 → electron_dedx__genie__secondary-proton-p-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 20/33 → electron_dedx__genie__tki-del_alpha_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 21/33 → electron_dedx__genie__tki-del_phi_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 22/33 → electron_dedx__genie__tki-del_Tp_lp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 23/33 → electron_dedx__genie__tki-del_alpha-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 24/33 → electron_dedx__genie__tki-del_phi-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 25/33 → electron_dedx__genie__tki-del_Tp-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 26/33 → electron_dedx__genie__opening_angle-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 27/33 → electron_dedx__genie__opening_angle_beam-res
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 28/33 → electron_dedx__genie__num-photons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 29/33 → electron_dedx__genie__num-electrons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 30/33 → electron_dedx__genie__num-muons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 31/33 → electron_dedx__genie__num-pions
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 32/33 → electron_dedx__genie__num-protons
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     histogram plot 33/33 → electron_dedx__genie__E_nu
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     bar breakdown …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline]     efficiency accumulators …
[DEBUG] cafpyana.pyanalib.chunked_selection: [pipeline] <<< stage='electron_dedx' finished
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_45.df for keys ['evt', 'trk', 'hdr', 'mcnu']
[DEBUG] cafpyana.analysis_village.nueNp0Pi.event_selection: Keys available in /exp/sbnd/data/users/micarrig/nueNp0Pi/selection_v3/output_v1_45.df: ['evt', 'trk', 'hdr', 'mcnu']

KeyboardInterrupt:

In [ ]:
import analysis_village.nueNp0Pi.config.stages as stages_mod
from analysis_village.nueNp0Pi.config.plots import VariableConfig

stages_mod.EVT_BREAKDOWN_TYPE = "topology"           # "topology" | "genie" | "pdg"
stages_mod.EVT_BREAKDOWN_DIR_NAME = f"selection_{stages_mod.EVT_BREAKDOWN_TYPE}"

stages_mod.DISABLE_EFFICIENCY_ACCUMULATION = True

stages_mod.N_MINUS_1_STAGE_KEYS = [
    "no_muons",
    "no_pions",
    "no_photons",
    "good_electron",
    "good_proton",
    "electron_softmax", 
    "electron_primary",
    "proton_softmax",
    "electron_vertex_distance",
    "electron_dedx"]
stages_mod.N_MINUS_1_VARS = {
    "no_muons": [VariableConfig.num_muons(), VariableConfig.leading_muon_ke()],
    "no_pions": [VariableConfig.num_pions(), VariableConfig.leading_pion_ke()],
    "no_photons": [VariableConfig.num_photons()], #VariableConfig.leading_photon_ke()],
    "good_electron": [VariableConfig.num_electrons(), VariableConfig.electron_energy()],
    "good_proton": [VariableConfig.num_protons(), VariableConfig.leading_proton_ke(), VariableConfig.proton_momentum()],
    "electron_softmax": [VariableConfig.electron_softmax_score()],
    "electron_primary": [VariableConfig.electron_primary_score()],
    "proton_softmax": [VariableConfig.proton_softmax_score()],
    "electron_vertex_distance": [VariableConfig.electron_vertex_distance()],
    "electron_dedx": [VariableConfig.electron_dedx()],
}

pipeline = build_event_selection_pipeline(batch_cfg)
batch_result = pipeline.run_full()

[event_selection] mc: looking in /Users/micarrig/Desktop/SBND/data/*.df
[event_selection] mc: found 1 file(s)
[event_selection] sample=mc  files=1  total=2.44 GiB
[event_selection] 1 job(s) under size budget
  mc batch_0000: 1 file(s), 2.435 GiB
[event_selection] WORK_BASE=/Users/micarrig/Desktop/SBND/cafpyana/plots
[event_selection] BATCHES_DIR=/Users/micarrig/Desktop/SBND/cafpyana/plots/batches
[event_selection] sample=mc batch_0000  files=1  size=2.435 GiB

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=48 (electron-e[topology], proton-p[topology], tki-del_Tp[topology], tki-del_alpha[topology], tki-del_phi[topology], tki-del_Tp_lp[topology], tki-del_alpha_lp[topology], tki-del_phi_lp[topology], opening_angle[topology], opening_angle_beam[topology], electron-e-res[topology], electron-dedx[topology], electron-vertex-distance[topology], electron-softmax-score[topology], electron-primary-score[topology], proton-softmax-score[topology], secondary-proton-p[topology], proton-p-res[topology], secondary-proton-p-res[topology], tki-del_alpha_lp-res[topology], tki-del_phi_lp-res[topology], tki-del_Tp_lp-res[topology], tki-del_alpha-res[topology], tki-del_phi-res[topology], tki-del_Tp-res[topology], opening_angle-res[topology], opening_angle_beam-res[topology], num-photons[topology], num-electrons[topology], num-muons[topology], num-pions[topology], num-protons[topology], E_nu[topology], num-muons[topology]+n_minus_1_no_muons, leading_muon_ke[topology]+n_minus_1_no_muons, num-pions[topology]+n_minus_1_no_pions, leading_pion_ke[topology]+n_minus_1_no_pions, num-photons[topology]+n_minus_1_no_photons, num-electrons[topology]+n_minus_1_good_electron, electron-e[topology]+n_minus_1_good_electron, num-protons[topology]+n_minus_1_good_proton, leading_proton_ke[topology]+n_minus_1_good_proton, proton-p[topology]+n_minus_1_good_proton, electron-softmax-score[topology]+n_minus_1_electron_softmax, electron-primary-score[topology]+n_minus_1_electron_primary, proton-softmax-score[topology]+n_minus_1_proton_softmax, electron-vertex-distance[topology]+n_minus_1_electron_vertex_distance, electron-dedx[topology]+n_minus_1_electron_dedx)  flags=eff,breakdown
[DEBUG] cafpyana.pyanalib.split_df_helpers_new: [split_df_helpers_new.py]: Loading 2 splits from /Users/micarrig/Desktop/SBND/data/output_v1_0.df for keys ['evt', 'trk', 'hdr']
/Users/micarrig/Desktop/SBND/cafpyana/pyanalib/split_df_helpers_new.py:74: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  out[col] = s.astype(bool)
/Users/micarrig/Desktop/SBND/cafpyana/pyanalib/split_df_helpers_new.py:74: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  out[col] = s.astype(bool)
/Users/micarrig/Desktop/SBND/cafpyana/pyanalib/split_df_helpers_new.py:74: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  out[col] = s.astype(bool)
/Users/micarrig/Desktop/SBND/cafpyana/pyanalib/split_df_helpers_new.py:74: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  out[col] = s.astype(bool)
/Users/micarrig/Desktop/SBND/cafpyana/pyanalib/split_df_helpers_new.py:74: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  out[col] = s.astype(bool)
/Users/micarrig/Desktop/SBND/cafpyana/pyanalib/split_df_helpers_new.py:74: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  out[col] = s.astype(bool)
/Users/micarrig/Desktop/SBND/cafpyana/pyanalib/split_df_helpers_new.py:74: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  out[col] = s.astype(bool)
/Users/micarrig/Desktop/SBND/cafpyana/pyanalib/split_df_helpers_new.py:74: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  out[col] = s.astype(bool)
/Users/micarrig/Desktop/SBND/cafpyana/pyanalib/split_df_helpers_new.py:74: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  out[col] = s.astype(bool)
/Users/micarrig/Desktop/SBND/cafpyana/pyanalib/split_df_helpers_new.py:74: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  out[col] = s.astype(bool)
/Users/micarrig/Desktop/SBND/cafpyana/pyanalib/split_df_helpers_new.py:74: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  out[col] = s.astype(bool)
/Users/micarrig/Desktop/SBND/cafpyana/pyanalib/split_df_helpers_new.py:74: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  out[col] = s.astype(bool)
/Users/micarrig/Desktop/SBND/cafpyana/pyanalib/split_df_helpers_new.py:74: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  out[col] = s.astype(bool)
/Users/micarrig/Desktop/SBND/cafpyana/pyanalib/split_df_helpers_new.py:74: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  out[col] = s.astype(bool)
/Users/micarrig/Desktop/SBND/cafpyana/pyanalib/split_df_helpers_new.py:74: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  out[col] = s.astype(bool)
/Users/micarrig/Desktop/SBND/cafpyana/pyanalib/split_df_helpers_new.py:74: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  out[col] = s.astype(bool)
/Users/micarrig/Desktop/SBND/cafpyana/pyanalib/split_df_helpers_new.py:74: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy

  out[col] = s.astype(bool)
/Users/micarrig/Desktop/SBND/cafpyana/pyanalib/split_df_helpers_new.py:74: FutureWarning: ChainedAssignmentError: behaviour will change in pandas 3.0!
You are setting values through chained assignment. Currently this works in certain cases, but when using Copy-on-Write (which will become the default behaviour in pandas 3.0) this will never work to update the original DataFrame or Series, because the intermediate object on which we are setting values will behave as a copy.
A typical example is when you are setting values in a column of a DataFrame, like:

df["col"][row_indexer] = value

Use `df.loc[row_indexer, "col"] = values` instead, to perform the assignment in a single step and ensure this keeps updating the original `df`.


[event_selection] done sample=mc batch_0000  n_evt=507555  pot=3.762e+18
[event_selection] sample=mc wrote 1 batch pickle(s)

[INFO] cafpyana.pyanalib.chunked_selection: aggregating 1 chunk file(s)
[INFO] cafpyana.pyanalib.chunked_selection: merging samples: ['mc']
[INFO] cafpyana.pyanalib.chunked_selection: applied global exposure scales: {'scale_mc': 1.0, 'scale_dirt': 1.0, 'scale_intime': 0.0, 'scale_offbeam': 0.0}

[aggregate] sample=mc -> 1 chunks
[aggregate] sample=data -> 0 chunks
[aggregate] sample=intime -> 0 chunks
[aggregate] sample=offbeam -> 0 chunks
[aggregate] sample=dirt -> 0 chunks
[aggregate] aggregating 1 chunks for sample=mc
[aggregate] exposure totals: data_pot=0.000e+00 bnb_gates=0.000e+00 mc_pot=3.762e+18 dirt_pot=0.000e+00 intime_gates=0.000e+00 offbeam_gates=0.000e+00
[aggregate] applied global scales: {'scale_mc': 1.0, 'scale_dirt': 1.0, 'scale_intime': 0.0, 'scale_offbeam': 0.0}
[aggregate] data_pot (legend)=3.762e+18 -> POT label=3.76$\times 10^{18}$
[aggregate] systematics disk root: None

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=48 (electron-e[topology], proton-p[topology], tki-del_Tp[topology], tki-del_alpha[topology], tki-del_phi[topology], tki-del_Tp_lp[topology], tki-del_alpha_lp[topology], tki-del_phi_lp[topology], opening_angle[topology], opening_angle_beam[topology], electron-e-res[topology], electron-dedx[topology], electron-vertex-distance[topology], electron-softmax-score[topology], electron-primary-score[topology], proton-softmax-score[topology], secondary-proton-p[topology], proton-p-res[topology], secondary-proton-p-res[topology], tki-del_alpha_lp-res[topology], tki-del_phi_lp-res[topology], tki-del_Tp_lp-res[topology], tki-del_alpha-res[topology], tki-del_phi-res[topology], tki-del_Tp-res[topology], opening_angle-res[topology], opening_angle_beam-res[topology], num-photons[topology], num-electrons[topology], num-muons[topology], num-pions[topology], num-protons[topology], E_nu[topology], num-muons[topology]+n_minus_1_no_muons, leading_muon_ke[topology]+n_minus_1_no_muons, num-pions[topology]+n_minus_1_no_pions, leading_pion_ke[topology]+n_minus_1_no_pions, num-photons[topology]+n_minus_1_no_photons, num-electrons[topology]+n_minus_1_good_electron, electron-e[topology]+n_minus_1_good_electron, num-protons[topology]+n_minus_1_good_proton, leading_proton_ke[topology]+n_minus_1_good_proton, proton-p[topology]+n_minus_1_good_proton, electron-softmax-score[topology]+n_minus_1_electron_softmax, electron-primary-score[topology]+n_minus_1_electron_primary, proton-softmax-score[topology]+n_minus_1_proton_softmax, electron-vertex-distance[topology]+n_minus_1_electron_vertex_distance, electron-dedx[topology]+n_minus_1_electron_dedx)  flags=eff,breakdown

[aggregate] overlay plots without syst covariance (49 plots, 37 distinct var_save_name): E_nu, electron-dedx, electron-e, electron-e-res, electron-primary-score, electron-softmax-score, electron-vertex-distance, leading_muon_ke, leading_pion_ke, leading_proton_ke, num-electrons, num-muons, num-photons, num-pions, num-protons, opening_angle, opening_angle-res, opening_angle_beam, opening_angle_beam-res, particle_ke, proton-p, proton-p-res, proton-softmax-score, secondary-proton-p, secondary-proton-p-res, tki-del_Tp, tki-del_Tp-res, tki-del_Tp_lp, tki-del_Tp_lp-res, tki-del_alpha, tki-del_alpha-res, tki-del_alpha_lp, tki-del_alpha_lp-res, tki-del_phi, tki-del_phi-res, tki-del_phi_lp, tki-del_phi_lp-res

[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages: [pipeline] built 14 stages:
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [00] allreco                    cut=no     plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [01] is_fiducial                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [02] is_flash_matched           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [03] is_contained               cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [04] no_muons                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [05] no_pions                   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [06] no_photons                 cut=yes    plots=1 (particle_ke[pdg])  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [07] good_electron              cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [08] good_proton                cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [09] electron_softmax           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [10] electron_primary           cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [11] proton_softmax             cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [12] electron_vertex_distance   cut=yes    plots=0 (—)  flags=eff,breakdown
[DEBUG] cafpyana.analysis_village.nueNp0Pi.config.stages:   [13] electron_dedx              cut=yes    plots=48 (electron-e[topology], proton-p[topology], tki-del_Tp[topology], tki-del_alpha[topology], tki-del_phi[topology], tki-del_Tp_lp[topology], tki-del_alpha_lp[topology], tki-del_phi_lp[topology], opening_angle[topology], opening_angle_beam[topology], electron-e-res[topology], electron-dedx[topology], electron-vertex-distance[topology], electron-softmax-score[topology], electron-primary-score[topology], proton-softmax-score[topology], secondary-proton-p[topology], proton-p-res[topology], secondary-proton-p-res[topology], tki-del_alpha_lp-res[topology], tki-del_phi_lp-res[topology], tki-del_Tp_lp-res[topology], tki-del_alpha-res[topology], tki-del_phi-res[topology], tki-del_Tp-res[topology], opening_angle-res[topology], opening_angle_beam-res[topology], num-photons[topology], num-electrons[topology], num-muons[topology], num-pions[topology], num-protons[topology], E_nu[topology], num-muons[topology]+n_minus_1_no_muons, leading_muon_ke[topology]+n_minus_1_no_muons, num-pions[topology]+n_minus_1_no_pions, leading_pion_ke[topology]+n_minus_1_no_pions, num-photons[topology]+n_minus_1_no_photons, num-electrons[topology]+n_minus_1_good_electron, electron-e[topology]+n_minus_1_good_electron, num-protons[topology]+n_minus_1_good_proton, leading_proton_ke[topology]+n_minus_1_good_proton, proton-p[topology]+n_minus_1_good_proton, electron-softmax-score[topology]+n_minus_1_electron_softmax, electron-primary-score[topology]+n_minus_1_electron_primary, proton-softmax-score[topology]+n_minus_1_proton_softmax, electron-vertex-distance[topology]+n_minus_1_electron_vertex_distance, electron-dedx[topology]+n_minus_1_electron_dedx)  flags=eff,breakdown

[aggregate] no efficiency data -> skipping
[aggregate] wrote /Users/micarrig/Desktop/SBND/cafpyana/plots/event_selection--20260817/pkl/merged_histdata.pkl
[event_selection] DONE plots -> /Users/micarrig/Desktop/SBND/cafpyana/plots/event_selection--20260817

# Debug

In [9]:
import uproot

pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [10]:
f_medulla = uproot.open("/exp/sbnd/app/users/micarrig/nueCCNp/output_nueCCNp_mc_5e18.root:events/signal/all", library="pd")

df_medulla = f_medulla.arrays(library="pd")

hdf_path = '/nashome/m/micarrig/sbnd/nueCCNp/cafpyana/test.df'
key = 'evt'

with pd.HDFStore(hdf_path, mode='r') as store:
    chunks = sorted(k for k in store.keys() if k.strip('/').startswith(key))
    print(f"Found {len(chunks)} chunks for key '{key}': {chunks}")
    df = pd.concat([store[k] for k in chunks])

Found 1 chunks for key 'evt': ['/evt_0']

In [6]:
df_medulla

KeyboardInterrupt:

In [7]:
df

KeyboardInterrupt:

In [11]:
# medulla signal events

signal_mask = (df_medulla['true_category'] == 0) | (df_medulla['true_category'] == 1)

df_medulla.loc[signal_mask, ['Run', 'Subrun', 'Evt']]

       Run  Subrun  Evt
1776     3      86   37
7283     4      75   88
16228    7      57   38
18403    8      49   98
21709    9      76   48
37216   15      11    2
59343   22      52   68
60266   22      79   89
62300   23      20   69
84673   30      52   66
86520   30      94   52

In [12]:
# cafpyana signal events

signal_mask = (df.rec.dlp_true['true_signal1p'] == True) | (df.rec.dlp_true['true_signalNp'] == True)

df.loc[signal_mask, ['run', 'subrun', 'evt']]

                              run subrun evt




__ntuple entry rec.dlp..index
0        145   0                3     86  37
         599   1                4     75  88
         1334  2                7     57  38
         1519  4                8     49  98
         1781  1                9     76  48
         3037  0               15     11   2
         4829  0               22     52  68
         4902  0               22     79  89
         5067  1               23     20  69
         7061  8               30     94  52

In [139]:
pd.concat([
    df.loc[signal_mask, ['run', 'subrun', 'evt']],
    df.loc[signal_mask].rec.dlp_true[['proton_energy_true', 'ele_energy_true', 'muon_energy_true', 'pion_energy_true', 'photon_energy_true', 'pion_mask_true', 'photon_mask_true', 'true_signal1p', 'true_signalNp']]
], axis=1)

                               (run, , , , )  (subrun, , , , )  (evt, , , , )  \
__ntuple entry rec.dlp..index
0        145   0                           3                86             37
         599   1                           4                75             88
         1334  2                           7                57             38
         1519  4                           8                49             98
         1781  1                           9                76             48
         3037  0                          15                11              2
         3153  1                          15                78             78
         3761  5                          18                11             49
               8                          18                11             49
         4829  0                          22                52             68
         4902  0                          22                79             89
         5067  1                          23                20             69
         5684  0                          25                75             23
         7061  8                          30                94             52

                               (proton_energy_true, , )  \
__ntuple entry rec.dlp..index
0        145   0                             398.448205
         599   1                             281.212945
         1334  2                             139.515302
         1519  4                              40.591564
         1781  1                             122.200287
         3037  0                              62.066490
         3153  1                             637.589779
         3761  5                              56.307022
               8                              56.307022
         4829  0                              86.648638
         4902  0                             318.260611
         5067  1                             225.633544
         5684  0                             530.166712
         7061  8                             273.176140

                               (ele_energy_true, , )  (muon_energy_true, , )  \
__ntuple entry rec.dlp..index
0        145   0                         2097.166883                     NaN
         599   1                          846.942876                     NaN
         1334  2                          528.199264                     NaN
         1519  4                          696.010582                     NaN
         1781  1                         1488.197271                     NaN
         3037  0                          664.116087                     NaN
         3153  1                          600.373314                     NaN
         3761  5                         1225.419225                     NaN
               8                         1225.419225                     NaN
         4829  0                          693.967585                     NaN
         4902  0                         1625.792760                     NaN
         5067  1                          819.915635                     NaN
         5684  0                         1288.906048                     NaN
         7061  8                         1269.506585                     NaN

                               (pion_energy_true, , )  \
__ntuple entry rec.dlp..index
0        145   0                                  NaN
         599   1                                  NaN
         1334  2                                  NaN
         1519  4                                  NaN
         1781  1                                  NaN
         3037  0                                  NaN
         3153  1                                  NaN
         3761  5                           145.550390
               8                           145.550390
         4829  0                                  NaN
         4902  0                                  NaN
         5067  1                                  NaN
         5684  0                           275.908238
         7061  8                                  NaN

                               (photon_energy_true, , ) (pion_mask_true, , )  \
__ntuple entry rec.dlp..index
0        145   0                                    NaN                False
         599   1                                    NaN                False
         1334  2                                    NaN                False
         1519  4                                    NaN                False
         1781  1                                    NaN                False
         3037  0                                    NaN                False
         3153  1                            1444.236486                False
         3761  5                                    NaN                 True
               8                                    NaN                 True
         4829  0                              70.404071                False
         4902  0                                    NaN                False
         5067  1                                    NaN                False
         5684  0                                    NaN                 True
         7061  8                                    NaN                False

                              (photon_mask_true, , )  (true_signal1p, , )  \
__ntuple entry rec.dlp..index
0        145   0                               False                 True
         599   1                               False                 True
         1334  2                               False                 True
         1519  4                               False                 True
         1781  1                               False                 True
         3037  0                               False                False
         3153  1                                True                 True
         3761  5                               False                 True
               8                               False                 True
         4829  0                               False                 True
         4902  0                               False                 True
         5067  1                               False                 True
         5684  0                               False                False
         7061  8                               False                False

                               (true_signalNp, , )
__ntuple entry rec.dlp..index
0        145   0                             False
         599   1                             False
         1334  2                             False
         1519  4                             False
         1781  1                             False
         3037  0                              True
         3153  1                             False
         3761  5                             False
               8                             False
         4829  0                             False
         4902  0                             False
         5067  1                             False
         5684  0                              True
         7061  8                              True

In [136]:
# medulla event type of events selected by cafpyana

keys = df.loc[signal_mask, ['run', 'subrun', 'evt']]
idx = pd.MultiIndex.from_frame(keys)
medulla_idx = pd.MultiIndex.from_arrays([df_medulla['Run'], df_medulla['Subrun'], df_medulla['Evt']])
df_medulla.loc[medulla_idx.isin(idx), ['Run', 'Subrun', 'Evt', 'true_category', 'true_leading_proton_ke', 'true_leading_proton_energy', 'true_leading_electron_energy', 'true_leading_electron_ke']]

,Run,Subrun,Evt,true_category,true_leading_proton_ke,true_leading_proton_energy,true_leading_electron_energy,true_leading_electron_ke
1776,3,86,37,1.0,398.448205,1336.720207,2097.166883,2097.166883
1777,3,86,37,10.0,NaN,NaN,42.931830,42.420759
1778,3,86,37,10.0,NaN,NaN,42.701891,42.190944
1779,3,86,37,10.0,NaN,NaN,85.238525,84.727269
1780,3,86,37,10.0,NaN,NaN,85.238525,84.727269
1781,3,86,37,8.0,75.194961,1013.466975,36.548029,36.037060
1782,3,86,37,10.0,NaN,NaN,45.595208,45.084181
1783,3,86,37,NaN,NaN,NaN,NaN,NaN
1784,3,86,37,10.0,NaN,NaN,33.782640,33.271718
1785,3,86,37,10.0,NaN,NaN,NaN,NaN
1786,3,86,37,10.0,NaN,NaN,NaN,NaN
1787,3,86,37,10.0,NaN,NaN,NaN,NaN
1788,3,86,37,8.0,NaN,NaN,NaN,NaN
7282,4,75,88,NaN,NaN,NaN,NaN,NaN
7283,4,75,88,1.0,281.212945,1219.484948,847.426979,846.942876
7284,4,75,88,10.0,NaN,NaN,109.286128,108.774756
7285,4,75,88,10.0,NaN,NaN,23.453544,22.942553
7286,4,75,88,10.0,NaN,NaN,35.192213,34.681220
7287,4,75,88,10.0,NaN,NaN,27.718865,27.207895
7288,4,75,88,10.0,NaN,NaN,15.665367,15.154384
7289,4,75,88,10.0,NaN,NaN,8.146726,7.635728
7290,4,75,88,10.0,NaN,NaN,87.670084,87.158752
7291,4,75,88,10.0,NaN,NaN,NaN,NaN
7292,4,75,88,10.0,NaN,NaN,87.670084,87.158752
7293,4,75,88,10.0,NaN,NaN,39.912287,39.401275
7294,4,75,88,10.0,NaN,NaN,NaN,NaN
16226,7,57,38,10.0,NaN,NaN,32.915996,32.404979
16227,7,57,38,10.0,NaN,NaN,726.862916,726.351881
16228,7,57,38,1.0,139.515302,1077.787314,528.717540,528.199264
16229,7,57,38,10.0,NaN,NaN,28.534908,28.023978
16230,7,57,38,10.0,NaN,NaN,72.877111,72.366351
16231,7,57,38,10.0,NaN,NaN,8.529849,8.018848
16232,7,57,38,10.0,NaN,NaN,726.862916,726.351881
16233,7,57,38,10.0,NaN,NaN,NaN,NaN
18399,8,49,98,NaN,NaN,NaN,NaN,NaN
18400,8,49,98,10.0,NaN,NaN,51.339027,50.828032
18401,8,49,98,NaN,NaN,NaN,NaN,NaN
18402,8,49,98,10.0,NaN,NaN,39.507822,38.996888
18403,8,49,98,1.0,40.591564,978.863576,696.493684,696.010582
18404,8,49,98,10.0,NaN,NaN,20.782981,20.271998
18405,8,49,98,10.0,NaN,NaN,19.804604,19.293608
18406,8,49,98,NaN,NaN,NaN,NaN,NaN
18407,8,49,98,10.0,NaN,NaN,31.337303,30.826315
18408,8,49,98,NaN,NaN,NaN,NaN,NaN
18409,8,49,98,10.0,NaN,NaN,51.339027,50.828032
18410,8,49,98,10.0,NaN,NaN,19.398083,18.887131
21708,9,76,48,10.0,NaN,NaN,45.246726,44.735606
21709,9,76,48,1.0,122.200287,1060.472287,1488.465425,1488.197271
21710,9,76,48,10.0,NaN,NaN,46.695130,46.184154
21711,9,76,48,10.0,NaN,NaN,NaN,NaN
21712,9,76,48,10.0,NaN,NaN,46.695130,46.184154
21713,9,76,48,8.0,19.259389,957.531401,10.758251,10.247249
21714,9,76,48,10.0,NaN,NaN,22.900515,22.389529
21715,9,76,48,10.0,NaN,NaN,NaN,NaN
21716,9,76,48,10.0,NaN,NaN,9.945208,9.434216
37216,15,11,2,0.0,62.066490,1000.338501,664.615537,664.116087
37217,15,11,2,10.0,NaN,NaN,14.678057,14.167061
37218,15,11,2,10.0,NaN,NaN,14.024974,13.513980
37219,15,11,2,10.0,NaN,NaN,10.976539,10.465540
37220,15,11,2,10.0,NaN,NaN,16.347281,15.836288
37221,15,11,2,10.0,NaN,NaN,NaN,NaN
37222,15,11,2,10.0,NaN,NaN,NaN,NaN
37223,15,11,2,10.0,27.345588,965.617600,NaN,NaN
37224,15,11,2,NaN,NaN,NaN,NaN,NaN
38587,15,78,78,10.0,NaN,NaN,NaN,NaN
38588,15,78,78,6.0,637.589779,1575.861779,600.884826,600.373314
38589,15,78,78,10.0,NaN,NaN,21.729401,21.218428
38590,15,78,78,10.0,NaN,NaN,68.664992,68.154088
38591,15,78,78,10.0,NaN,NaN,12.267343,11.756331
38592,15,78,78,10.0,NaN,NaN,NaN,NaN
38593,15,78,78,10.0,NaN,NaN,NaN,NaN
46196,18,11,49,10.0,NaN,NaN,217.832838,217.320412
46197,18,11,49,10.0,NaN,NaN,16.130876,15.619873
46198,18,11,49,10.0,NaN,NaN,68.394424,67.883466
46199,18,11,49,10.0,NaN,NaN,41.490633,40.979522
46200,18,11,49,10.0,NaN,NaN,94.601697,94.090485
46201,18,11,49,4.0,56.307022,994.579037,1225.746704,1225.419225
46202,18,11,49,10.0,NaN,NaN,73.923867,73.411977
46203,18,11,49,10.0,NaN,NaN,22.502420,21.991428
46204,18,11,49,4.0,56.307022,994.579037,1225.746704,1225.419225
59343,22,52,68,1.0,86.648638,1024.920646,694.491671,693.967585
59344,22,52,68,10.0,NaN,NaN,329.304032,328.784010
59345,22,52,68,NaN,NaN,NaN,NaN,NaN
59346,22,52,68,10.0,NaN,NaN,616.668409,616.179237
59347,22,52,68,10.0,NaN,NaN,56.270756,55.760052
59348,22,52,68,10.0,NaN,NaN,33.556823,33.045905
59349,22,52,68,10.0,NaN,NaN,12.551301,12.040306
59350,22,52,68,10.0,NaN,NaN,9.354722,8.843724
59351,22,52,68,10.0,NaN,NaN,137.383975,136.873237
59352,22,52,68,10.0,NaN,NaN,46.191290,45.680155
59353,22,52,68,10.0,NaN,NaN,10.644340,10.133347
59354,22,52,68,10.0,NaN,NaN,3.691685,3.180688
60266,22,79,89,1.0,318.260611,1256.532641,1626.308478,1625.792760
60267,22,79,89,10.0,NaN,NaN,63.899410,63.388731
60268,22,79,89,10.0,NaN,NaN,10.802701,10.291695
60269,22,79,89,10.0,NaN,NaN,24.785073,24.274005
60270,22,79,89,10.0,NaN,NaN,NaN,NaN
60271,22,79,89,10.0,NaN,NaN,10.802701,10.291695
60272,22,79,89,10.0,NaN,NaN,NaN,NaN
62299,23,20,69,NaN,NaN,NaN,NaN,NaN
62300,23,20,69,1.0,225.633544,1163.905572,820.444486,819.915635
62301,23,20,69,10.0,NaN,NaN,7.698231,7.187236
62302,23,20,69,10.0,NaN,NaN,NaN,NaN
62303,23,20,69,10.0,NaN,NaN,41.257487,40.746523
62304,23,20,69,10.0,NaN,NaN,14.006257,13.495260
62305,23,20,69,10.0,NaN,NaN,75.283585,74.772948
62306,23,20,69,NaN,NaN,NaN,NaN,NaN
62307,23,20,69,NaN,NaN,NaN,NaN,NaN
62308,23,20,69,10.0,NaN,NaN,34.670823,34.159802
62309,23,20,69,10.0,NaN,NaN,59.183040,58.672013
62310,23,20,69,10.0,NaN,NaN,9.289522,8.778516
62311,23,20,69,10.0,NaN,NaN,9.289522,8.778516
62312,23,20,69,10.0,NaN,NaN,7.698231,7.187236
62313,23,20,69,10.0,NaN,NaN,5.985084,5.474087
62314,23,20,69,10.0,NaN,NaN,NaN,NaN
62315,23,20,69,10.0,NaN,NaN,9.289522,8.778516
62316,23,20,69,10.0,NaN,NaN,NaN,NaN
62317,23,20,69,10.0,NaN,NaN,NaN,NaN
69630,25,75,23,4.0,530.166712,1468.438801,1289.356313,1288.906048
69631,25,75,23,10.0,NaN,NaN,17.837097,17.326078
69632,25,75,23,NaN,NaN,NaN,NaN,NaN
69633,25,75,23,10.0,NaN,NaN,42.320164,41.809141
69634,25,75,23,10.0,NaN,NaN,40.807200,40.296063
69635,25,75,23,10.0,NaN,NaN,12.841127,12.330140
86512,30,94,52,NaN,NaN,NaN,NaN,NaN
86513,30,94,52,10.0,NaN,NaN,104.472426,103.961353
86514,30,94,52,10.0,NaN,NaN,219.256816,218.744518
86515,30,94,52,10.0,NaN,NaN,55.583028,55.072097
86516,30,94,52,10.0,NaN,NaN,80.756984,80.246315
86517,30,94,52,NaN,NaN,NaN,NaN,NaN
86518,30,94,52,10.0,NaN,NaN,548.573198,548.082151
86519,30,94,52,10.0,NaN,NaN,104.472426,103.961353
86520,30,94,52,0.0,273.176140,1211.448141,1270.100529,1269.506585
86521,30,94,52,10.0,NaN,NaN,93.896371,93.385538
86522,30,94,52,10.0,NaN,NaN,8.672931,8.161929
86523,30,94,52,10.0,NaN,NaN,NaN,NaN
86524,30,94,52,10.0,NaN,NaN,29.151718,28.640749
86525,30,94,52,10.0,NaN,NaN,NaN,NaN
86526,30,94,52,10.0,NaN,NaN,22.945412,22.434417
86527,30,94,52,NaN,NaN,NaN,NaN,NaN
86528,30,94,52,10.0,NaN,NaN,4.397592,3.886594
86529,30,94,52,10.0,NaN,NaN,11.563036,11.052053

In [130]:
# cafpyana event type of events selected by medulla

keys = df_medulla.loc[signal_mask, ['Run', 'Subrun', 'Evt']]
idx = pd.MultiIndex.from_frame(keys)
cafpyana_idx = pd.MultiIndex.from_arrays([df['run'], df['subrun'], df['evt']])
evt_info = df.loc[cafpyana_idx.isin(idx), ['run', 'subrun', 'evt']]
branches = df.loc[cafpyana_idx.isin(idx)].rec.dlp_true[['true_signal1p', 'true_signalNp', 'bkgd_oofv', 'bkgd_oops', \
    'bkgd_pi', 'bkgd_mu', 'bkgd_photon', 'bkgd_nueOther', 'bkgd_numu', 'bkgd_nc', 'bkgd_other', \
    'muon_energy_true', 'ele_energy_true', 'proton_energy_true', 'muon_count_true']]

pd.concat([
    evt_info,
    branches
], axis=1)

                               (run, , , , )  (subrun, , , , )  (evt, , , , )  \
__ntuple entry rec.dlp..index
0        145   0                           3                86             37
               1                           3                86             37
               2                           3                86             37
               3                           3                86             37
               4                           3                86             37
               5                           3                86             37
               6                           3                86             37
               7                           3                86             37
               8                           3                86             37
               9                           3                86             37
               10                          3                86             37
               11                          3                86             37
               12                          3                86             37
         599   0                           4                75             88
               1                           4                75             88
               2                           4                75             88
               3                           4                75             88
               4                           4                75             88
               5                           4                75             88
               6                           4                75             88
               7                           4                75             88
               8                           4                75             88
               9                           4                75             88
               10                          4                75             88
               11                          4                75             88
               12                          4                75             88
         1334  0                           7                57             38
               1                           7                57             38
               2                           7                57             38
               3                           7                57             38
               4                           7                57             38
               5                           7                57             38
               6                           7                57             38
               7                           7                57             38
         1519  0                           8                49             98
               1                           8                49             98
               2                           8                49             98
               3                           8                49             98
               4                           8                49             98
               5                           8                49             98
               6                           8                49             98
               7                           8                49             98
               8                           8                49             98
               9                           8                49             98
               10                          8                49             98
               11                          8                49             98
         1781  0                           9                76             48
               1                           9                76             48
               2                           9                76             48
               3                           9                76             48
               4                           9                76             48
               5                           9                76             48
               6                           9                76             48
               7                           9                76             48
               8                           9                76             48
         3037  0                          15                11              2
               1                          15                11              2
               2                          15                11              2
               3                          15                11              2
               4                          15                11              2
               5                          15                11              2
               6                          15                11              2
               7                          15                11              2
               8                          15                11              2
         4829  0                          22                52             68
               1                          22                52             68
               2                          22                52             68
               3                          22                52             68
               4                          22                52             68
               5                          22                52             68
               6                          22                52             68
               7                          22                52             68
               8                          22                52             68
               9                          22                52             68
               10                         22                52             68
               11                         22                52             68
         4902  0                          22                79             89
               1                          22                79             89
               2                          22                79             89
               3                          22                79             89
               4                          22                79             89
               5                          22                79             89
               6                          22                79             89
         5067  0                          23                20             69
               1                          23                20             69
               2                          23                20             69
               3                          23                20             69
               4                          23                20             69
               5                          23                20             69
               6                          23                20             69
               7                          23                20             69
               8                          23                20             69
               9                          23                20             69
               10                         23                20             69
               11                         23                20             69
               12                         23                20             69
               13                         23                20             69
               14                         23                20             69
               15                         23                20             69
               16                         23                20             69
               17                         23                20             69
               18                         23                20             69
         6911  0                          30                52             66
               1                          30                52             66
               2                          30                52             66
               3                          30                52             66
               4                          30                52             66
               5                          30                52             66
               6                          30                52             66
               7                          30                52             66
               8                          30                52             66
               9                          30                52             66
               10                         30                52             66
               11                         30                52             66
               12                         30                52             66
         7061  0                          30                94             52
               1                          30                94             52
               2                          30                94             52
               3                          30                94             52
               4                          30                94             52
               5                          30                94             52
               6                          30                94             52
               7                          30                94             52
               8                          30                94             52
               9                          30                94             52
               10                         30                94             52
               11                         30                94             52
               12                         30                94             52
               13                         30                94             52
               14                         30                94             52
               15                         30                94             52
               16                         30                94             52
               17                         30                94             52

                               (true_signal1p, , )  (true_signalNp, , )  \
__ntuple entry rec.dlp..index
0        145   0                              True                False
               1                             False                False
               2                             False                False
               3                             False                False
               4                             False                False
               5                             False                False
               6                             False                False
               7                             False                False
               8                             False                False
               9                             False                False
               10                            False                False
               11                            False                False
               12                            False                False
         599   0                             False                False
               1                              True                False
               2                             False                False
               3                             False                False
               4                             False                False
               5                             False                False
               6                             False                False
               7                             False                False
               8                             False                False
               9                             False                False
               10                            False                False
               11                            False                False
               12                            False                False
         1334  0                             False                False
               1                             False                False
               2                              True                False
               3                             False                False
               4                             False                False
               5                             False                False
               6                             False                False
               7                             False                False
         1519  0                             False                False
               1                             False                False
               2                             False                False
               3                             False                False
               4                              True                False
               5                             False                False
               6                             False                False
               7                             False                False
               8                             False                False
               9                             False                False
               10                            False                False
               11                            False                False
         1781  0                             False                False
               1                              True                False
               2                             False                False
               3                             False                False
               4                             False                False
               5                             False                False
               6                             False                False
               7                             False                False
               8                             False                False
         3037  0                             False                 True
               1                             False                False
               2                             False                False
               3                             False                False
               4                             False                False
               5                             False                False
               6                             False                False
               7                             False                False
               8                             False                False
         4829  0                              True                False
               1                             False                False
               2                             False                False
               3                             False                False
               4                             False                False
               5                             False                False
               6                             False                False
               7                             False                False
               8                             False                False
               9                             False                False
               10                            False                False
               11                            False                False
         4902  0                              True                False
               1                             False                False
               2                             False                False
               3                             False                False
               4                             False                False
               5                             False                False
               6                             False                False
         5067  0                             False                False
               1                              True                False
               2                             False                False
               3                             False                False
               4                             False                False
               5                             False                False
               6                             False                False
               7                             False                False
               8                             False                False
               9                             False                False
               10                            False                False
               11                            False                False
               12                            False                False
               13                            False                False
               14                            False                False
               15                            False                False
               16                            False                False
               17                            False                False
               18                            False                False
         6911  0                             False                False
               1                             False                False
               2                             False                False
               3                             False                False
               4                             False                False
               5                             False                False
               6                             False                False
               7                             False                False
               8                             False                False
               9                             False                False
               10                            False                False
               11                            False                False
               12                            False                False
         7061  0                             False                False
               1                             False                False
               2                             False                False
               3                             False                False
               4                             False                False
               5                             False                False
               6                             False                False
               7                             False                False
               8                             False                 True
               9                             False                False
               10                            False                False
               11                            False                False
               12                            False                False
               13                            False                False
               14                            False                False

In [63]:
signal_mask = (df_medulla['true_category'] == 0) | (df_medulla['true_category'] == 1)

df_medulla.loc[signal_mask, ['Run', 'Subrun', 'Evt', 'true_leading_muon_ke', 'true_leading_muon_energy']]

       Run  Subrun  Evt  true_leading_muon_ke  true_leading_muon_energy
1776     3      86   37                   NaN                       NaN
7283     4      75   88                   NaN                       NaN
16228    7      57   38                   NaN                       NaN
18403    8      49   98                   NaN                       NaN
21709    9      76   48                   NaN                       NaN
37216   15      11    2                   NaN                       NaN
59343   22      52   68                   NaN                       NaN
60266   22      79   89                   NaN                       NaN
62300   23      20   69                   NaN                       NaN
84673   30      52   66                   NaN                       NaN
86520   30      94   52                   NaN                       NaN

In [34]:
df_medulla[(df_medulla['Run'] == 4) & (df_medulla['Evt'] == 88) & (df_medulla['Subrun'] == 75)]

,reco_containment_cut,reco_cut_type,reco_dalphaT,reco_dpL,reco_dpL_lp,reco_dpT,reco_dpT_lp,reco_dphiT,reco_ele_beam_open_angle,reco_electron_multiplicity,reco_electron_softmax_cut,reco_fiducial_cut,reco_flash_cut,reco_flash_time,reco_has_electron,reco_has_proton,reco_is_data,reco_is_nu,reco_leading_ele_energy_cut,reco_leading_electron_axial_cut,reco_leading_electron_axial_spread,reco_leading_electron_azimuthal_angle,reco_leading_electron_calo_ke,reco_leading_electron_containment_cut,reco_leading_electron_csda_ke,reco_leading_electron_dedx,reco_leading_electron_directional_spread,reco_leading_electron_electron_softmax,reco_leading_electron_end_dir_x,reco_leading_electron_end_dir_y,reco_leading_electron_end_dir_z,reco_leading_electron_end_x,reco_leading_electron_end_y,reco_leading_electron_end_z,reco_leading_electron_energy,reco_leading_electron_ke,reco_leading_electron_length,reco_leading_electron_mcs_ke,reco_leading_electron_mip_softmax,reco_leading_electron_muon_softmax,reco_leading_electron_p,reco_leading_electron_photon_softmax,reco_leading_electron_pion_softmax,reco_leading_electron_polar_angle,reco_leading_electron_primary_softmax,reco_leading_electron_proton_softmax,reco_leading_electron_secondary_softmax,reco_leading_electron_start_dedx,reco_leading_electron_start_dir_x,reco_leading_electron_start_dir_y,reco_leading_electron_start_dir_z,reco_leading_electron_start_x,reco_leading_electron_start_y,reco_leading_electron_start_z,reco_leading_electron_vertex_distance,reco_leading_muon_azimuthal_angle,reco_leading_muon_energy,reco_leading_muon_ke,reco_leading_muon_muon_softmax,reco_leading_muon_p,reco_leading_muon_polar_angle,reco_leading_muon_primary_softmax,reco_leading_muon_start_dedx,reco_leading_photon_azimuthal_angle,reco_leading_photon_energy,reco_leading_photon_p,reco_leading_photon_photon_softmax,reco_leading_photon_polar_angle,reco_leading_photon_primary_softmax,reco_leading_photon_start_dedx,reco_leading_pion_azimuthal_angle,reco_leading_pion_energy,reco_leading_pion_ke,reco_leading_pion_p,reco_leading_pion_pion_softmax,reco_leading_pion_polar_angle,reco_leading_pion_primary_softmax,reco_leading_pion_start_dedx,reco_leading_proton_azimuthal_angle,reco_leading_proton_energy,reco_leading_proton_ke,reco_leading_proton_muon_softmax,reco_leading_proton_p,reco_leading_proton_pion_softmax,reco_leading_proton_polar_angle,reco_leading_proton_primary_softmax,reco_leading_proton_proton_softmax,reco_leading_proton_start_dedx,reco_leading_proton_vertex_distance,reco_muon_multiplicity,reco_no_charged_pions,reco_no_cut,reco_no_muons,reco_no_photons,reco_no_protons,reco_nonelectron_containment_cut,reco_opening_angle,reco_photon_multiplicity,reco_photon_multiplicity25,reco_pion_multiplicity,reco_pn,reco_pn_lp,reco_primary_softmax_cut,reco_proton_multiplicity,reco_proton_softmax_cut,reco_reco_interaction_type,reco_single_tpc_contained,reco_track_length,reco_two_photon_candidates,reco_valid_flashmatch,reco_vertex_distance_cut,reco_visible_energy,true_baseline,true_category,true_cc,true_containment_cut,true_cut_type,true_dalphaT,true_dpL,true_dpL_lp,true_dpT,true_dpT_lp,true_dphiT,true_ele_beam_open_angle,true_electron_multiplicity,true_fiducial_cut,true_flash_cut,true_hadronic_invariant_mass,true_has_electron,true_has_proton,true_interaction_mode,true_interaction_type,true_is_data,true_is_nu,true_leading_ele_energy_cut,true_leading_electron_azimuthal_angle,true_leading_electron_calo_ke,true_leading_electron_containment_cut,true_leading_electron_csda_ke,true_leading_electron_end_dir_x,true_leading_electron_end_dir_y,true_leading_electron_end_dir_z,true_leading_electron_end_x,true_leading_electron_end_y,true_leading_electron_end_z,true_leading_electron_energy,true_leading_electron_ke,true_leading_electron_length,true_leading_electron_mcs_ke,true_leading_electron_p,true_leading_electron_polar_angle,true_leading_electron_start_dir_x,true_leading_electron_start_dir_y,true_leading_electron_start_dir_z,true_leading_electron_start_x,true_leading_electron_start_y,true_leading_electron_start_z,true_leading_muon_azimuthal_angle,true_leading_muon_energy,true_leading_muon_ke,true_leading_muon_p,true_leading_muon_polar_angle,true_leading_photon_azimuthal_angle,true_leading_photon_energy,true_leading_photon_p,true_leading_photon_polar_angle,true_leading_pion_azimuthal_angle,true_leading_pion_energy,true_leading_pion_ke,true_leading_pion_p,true_leading_pion_polar_angle,true_leading_proton_azimuthal_angle,true_leading_proton_energy,true_leading_proton_ke,true_leading_proton_p,true_leading_proton_polar_angle,true_momentum_transfer,true_muon_multiplicity,true_neutrino_energy,true_neutrino_id,true_no_charged_pions,true_no_cut,true_no_muons,true_no_photons,true_no_protons,true_nonelectron_containment_cut,true_opening_angle,true_pdg,true_photon_multiplicity,true_photon_multiplicity25,true_pion_multiplicity,true_pn,true_pn_lp,true_proton_multiplicity,true_single_tpc_contained,true_track_length,true_two_photon_candidates,true_valid_flashmatch,true_visible_energy,Run,Subrun,Evt
7282,0.0,0.0,3.141593,-697.291156,NaN,928.325484,NaN,NaN,1.570796,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,-5.0,0.0,0.0,NaN,0.785347,4.262254,0.0,NaN,0.0,-1.000000,0.616815,NaN,NaN,NaN,NaN,NaN,NaN,4.773253,4.262254,-1.0,NaN,0.0,0.0,4.746718,0.383185,0.0,1.570796,0.413893,0.0,0.586107,-1.00000,0.707143,0.707071,0.000000,208.650024,109.050018,9.650002,-1.000000,-1.608537,974.605457,868.947083,0.871654,968.860901,1.861083,0.929437,1.993970,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,1161.035383,NaN,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.974605,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,4,75,88
7283,0.0,0.0,1.921460,-1566.680991,-832.693824,942.761688,1017.012722,0.537787,0.895970,2.0,1.0,1.0,0.0,NaN,1.0,1.0,0.0,-5.0,1.0,1.0,0.632061,0.356523,882.735474,1.0,NaN,1.0,0.011548,0.904122,NaN,NaN,NaN,NaN,NaN,NaN,883.246473,882.735474,-1.0,NaN,0.0,0.0,883.247375,0.095878,0.0,0.895970,0.999040,0.0,0.000960,1.86749,0.731715,0.272519,0.624762,-32.250000,16.649994,129.050018,0.887412,-1.427598,850.736133,745.077759,0.903481,844.149109,1.788308,0.956515,1.779359,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.176208,1220.537157,282.265076,0.000114,780.612854,0.000594,0.556962,0.920377,0.999292,4.25057,-1.0,1.0,1.0,1.0,0.0,1.0,0.0,0.0,0.623195,0.0,0.0,0.0,1828.466278,1314.417697,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,2.047148,124.149055,1.0,1.0,1.0,0.0,2.802382,60.889214,60.889214,959.909664,959.909664,2.278526,0.841598,1.0,1.0,0.0,1.008192,1.0,1.0,0.0,1001.0,0.0,-5.0,1.0,0.277066,969.906494,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,847.426979,846.942876,-1.0,NaN,847.426819,0.841598,0.717269,0.203977,0.666272,-33.149994,16.649994,127.849998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.140133,1219.484948,281.212945,778.966736,0.570001,0.731523,0.0,1.308812,1.0,1.0,1.0,1.0,1.0,0.0,1.0,0.604924,12.0,0.0,0.0,0.0,961.838895,961.838895,1.0,0.0,1.0,0.0,0.0,1.159540,4,75,88
7284,0.0,0.0,3.141593,-479.284839,NaN,1124.240837,NaN,NaN,2.095623,0.0,1.0,0.0,0.0,NaN,0.0,0.0,0.0,-5.0,0.0,0.0,NaN,2.071518,54.409599,1.0,NaN,0.0,-1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,54.920598,54.409599,-1.0,NaN,0.0,0.0,54.919209,0.000000,0.0,2.095623,0.000000,0.0,1.000000,-1.00000,-0.415448,0.759170,-0.501063,-91.350006,133.050018,80.150002,-1.000000,1.949323,1569.834888,1464.176514,0.995173,1566.274902,2.340984,0.983543,1.777453,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,1222.142142,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.569835,NaN,10.0,NaN,0.0,0.0,3.141593,-12914.713219,NaN,30222.435315,NaN,NaN,0.844288,0.0,0.0,0.0,-1.000000,0.0,0.0,NaN,NaN,0.0,-5.0,0.0,-1.069410,45.720627,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,109.286128,108.774756,-1.0,NaN,109.284935,0.844288,0.359279,-0.655494,0.664263,160.950012,-151.350006,375.649994,-1.190251,41820.387047,41714.837066,41820.253906,0.807664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,1.0,NaN,-1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,0.0,0.0,32866.174312,NaN,0.0,0.0,1.0,0.0,0.0,41.820387,4,75,88
7285,0.0,0.0,NaN,0.000000,NaN,0.000000,NaN,NaN,1.228466,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,-5.0,0.0,0.0,NaN,-0.712358,22.973112,1.0,NaN,0.0,-1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,23.484111,22.973112,-1.0,NaN,0.0,0.0,23.479527,0.000000,0.0,1.228466,0.000000,0.0,1.000000,-1.00000,0.712908,-0.615694,0.335684,24.450012,193.649994,138.649994,-1.000000,1.955862,604.152942,498.494568,0.491688,594.841797,2.346881,0.796603,2.207458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,0.000000,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.000000,NaN,10.0,NaN,0.0,0.0,NaN,-2124.408897,NaN,4974.880169,NaN,NaN,1.010278,0.0,0.0,0.0,-1.000000,0.0,0.0,NaN,NaN,0.0,-5.0,0.0,-1.142199,22.794989,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,23.453544,22.942553,-1.0,NaN,23.447977,1.010278,0.352001,-0.770370,0.531625,28.049988,191.250000,140.149994,-1.186068,6889.848838,6784.184204,6889.038574,0.806897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,1.0,NaN,-1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,0.0,0.0,5409.486654,NaN,0.0,0.0,1.0,0.0,0.0,6.889849,4,75,88
7286,0.0,0.0,NaN,0.000000,NaN,0.000000,NaN,NaN,1.905562,0.0,1.0,0.0,0.0,NaN,0.0,0.0,0.0,-5.0,0.0,0.0,NaN,2.594674,38.922340,0.0,NaN,0.0,-1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,39.433339,38.922340,-1.0,NaN,0.0,0.0,39.431015,0.000000,0.0,1.905562,0.000000,0.0,1.000000,-1.00000,-0.806716,0.491188,-0.328548,0.750000,134.250000,456.650055,-1.000000,-0.139468,161.810856,56.152481,0.813115,122.552101,1.546380,0.835028,2.008505,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,0.000000,NaN,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.000000,NaN,10.0,NaN,0.0,0.0,3.141593,-1962.541111,NaN,2086.470994,NaN,NaN,1.591422,0.0,0.0,0.0,-1.000000,0.0,0.0,NaN,NaN,0.0,-5.0,0.0,-0.110361,33.806885,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,35.192213,34.681220,-1.0,NaN,35.188503,1.591422,0.993705,-0.110114,-0.020624,0.750000,134.250000,456.649994,-0.495944,2093.228108,1987.571066,2090.559814,1.508243,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,1.0,NaN,-1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,0.0,0.0,2864.424693,NaN,0.0,0.0,1.0,0.0,0.0,2.093228,4,75,88
7287,0.0,0.0,3.141593,-368.745044,NaN,685.742668,NaN,NaN,1.737519,0.0,1.0,0.0,0.0,NaN,0.0,0.0,0.0,-5.0,0.0,0.0,NaN,-2.466634,26.204874,1.0,NaN,0.0,-1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,26.715873,26.204874,-1.0,NaN,0.0,0.0,26.711966,0.000000,0.0,1.737519,0.000000,0.0,1.000000,-1.00000,-0.769907,-0.616201,-0.165952,48.149994,-60.449997,26.750000,-1.000000,-1.728369,837.136829,731.478455,0.945048,830.441956,2.170051,0.871553,1.778433,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,778.598686,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.837137,NaN,10.0,NaN,0.0,0.0,3.141593,-553.670407,NaN,975.000036,NaN,NaN,1.251296,0.0,0.0,0.0,-1.000000,0.0,0.0,NaN,NaN,0.0,-5.0,0.0,0.937784,26.049662,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27.718865,27.207895,-1.0,NaN,27.714155,1.251296,0.561638,0.765447,0.314092,48.149994,-60.150009,26.150002,-1.650703,1145.392392,1039.733832,1140.508667,2.116270,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,1.0,NaN,-1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,0.0,0.0,1121.238596,NaN,0.0,0.0,1.0,0.0,0.0,1.145392,4,75,88
7288,0.0,0.0,NaN,-908.842807,NaN,1105.669807,NaN,NaN,2.186288,0.0,1.0,0.0,0.0,NaN,0.0,0.0,0.0,-5.0,0.0,0.0,NaN,-0.785398,2.519549,1.0,NaN,0.0,-1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,3.030548,2.519549,-1.0,NaN,0.0,0.0,2.987999,0.000000,0.0,2.186288,0.000000,0.0,1.000000,-1.00000,0.577345,-0.577345,-0.577360,132.450012,-38.850006,33.349998,-1.000000,-1.070508,1133.125171,1027.466797,0.970862,1128.187988,1.370664,0.988886,1.727107,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,1431.258527,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.133125,NaN,10.0,NaN,0.0,0.0,3.141593,-1349.742317,NaN,1829.188867,NaN,NaN,1.122458,0.0,0.0,0.0,-1.000000,0.0,0.0,NaN,NaN,0.0,-5.0,0.0,-0.888101,2.737085,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,15.665367,15.154384,-1.0,NaN,15.657031,1.122458,0.568535,-0.699194,0.433469,161.850006,-83.250000,48.049995,-1.108056,1918.477302,1812.819086,1915.565552,1.269350,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,1.0,NaN,-1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,0.0,0.0,2273.265543,NaN,0.0,0.0,1.0,0.0,0.0,1.918477,4,75,88
7289,0.0,0.0,NaN,-1104.140125,NaN,1501.423929,NaN,NaN,0.785424,0.0,1.0,1.0,1.0,0.502926,0.0,0.0,0.0,-5.0,0.0,0.0,NaN,-1.570796,2.625529,1.0,NaN,0.0,-1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,3.136528,2.625529,-1.0,NaN,0.0,0.0,3.095470,0.000000,0.0,0.785423,0.000000,0.0,1.000000,-1.00000,0.000000,-0.707125,0.707089,-94.050003,-120.150009,128.450012,-1.000000,-1.109399,1577.953663,1472.295288,0.934491,1574.411987,1.265111,0.982867,3.646608,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,1863.705779,NaN,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,1.577954,NaN,10.0,NaN,0.0,0.0,3.141593,-1292.657340,NaN,1795.801279,NaN,NaN,1.072305,0.0,0.0,0.0,-1.000000,0.0,0.0,NaN,NaN,0.0,-5.0,0.0,-0.840275,5.736906,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8.146726,7.635728,-1.0,NaN,8.130684,1.072304,0.586056,-0.654185,0.478101,-96.149979,-118.950012,127.249992,-1.136865,1898.039359,1792.379953,1895.096191,1.245651,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,1.0,NaN,-1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,0.0,0.0,2212.660216,NaN,0.0,0.0,1.0,0.0,0.0,1.898039,4,75,88
7290,0.0,0.0,3.141593,-1221.093403,NaN,1503.052811,NaN,NaN,1.991469,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,-5.0,0.0,0.0,NaN,-2.634015,34.180283,0.0,NaN,0.0,-1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,34.691282,34.180283,-1.0,NaN,0.0,0.0,34.688503,0.000000,0.0,1.991469,0.000000,0.0,1.000000,-1.00000,-0.797731,-0.443684,-0.408375,-17.250000,34.049988,212.150024,-1.000000,-2.884374,1540.177540,1434.519165,0.629369,1536.548828,1.779981,0.699056,2.106690,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,1936.552827,NaN,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.540178,NaN,10.0,NaN,1.0,0.0,3.141593,-9024.773689,NaN,10669.843379,NaN,NaN,1.682467,0.0,0.0,0.0,-1.000000,0.0,0.0,NaN,NaN,0.0,-5.0,0.0,-2.903961,36.976971,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.670084,87.158752,-1.0,NaN,87.668594,1.682467,-0.965845,-0.233935,-0.111439,-4.950012,37.950012,214.550018,-2.854538,10820.396736,10714.748641,10819.880859,1.737524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,1.0,NaN,-1.0,1.0,1.0,0.0,1.0,1.0,1.0,NaN,NaN,0.0,0.0,0.0,13974.694912,NaN,0.0,0.0,1.0,0.0,0.0,10.820397,4,75,88
7291,0.0,0.0,3.141593,-8208.289722,NaN,9723.732863,NaN,NaN,-1.000000,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,-5.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.685153,9864.306812,9758.648438,0.625676,9863.741211,1.402108,0.763761,2.411836,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,12725.054065,NaN,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,9.864307,NaN,10.0,NaN,0.0,0.0,3.141593,-12215.344193,NaN,15432.923501,NaN,NaN,-1.000000,0.0,0.0,0.0,-1.000000,0.0,0.0,NaN,NaN,0.0,-5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.688531,15857.143265,15751.461949,15856.791016,1.339060,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,1.0,NaN,-1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,0.0,0.0,19682.219426,NaN,0.0,0.0,1.0,0.0,0.0,15.857143,4,75,88
7292,0.0,0.0,3.141593,-1242.972004,NaN,1574.290962,NaN,NaN,-1.000000,0.0,0.0,1.0,0.0,NaN,0.0,0.0,0.0,-5.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-2.933566,1622.939258,1517.280884,0.512161,1619.495972,1.807625,0.523604,2.122994,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,2005.834349,NaN,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,1.622939,NaN,10.0,NaN,1.0,0.0,3.141593,-9024.773689,NaN,10669.843379,NaN,NaN,1.682467,0.0,0.0,0.0,-1.000000,0.0,0.0,NaN,NaN,0.0,-5.0,0.0,-2.903961,36.976971,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,87.670084,87.158752,-1.0,NaN,87.668594,1.682467,-0.965845,-0.233935,-0.111439,-4.950012,37.950012,214.550018,-2.854538,10820.396736,10714.748641,10819.880859,1.737524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,1.0,NaN,-1.0,1.0,1.0,0.0,1.0,1.0,1.0,NaN,NaN,0.0,0.0,0.0,13974.694912,NaN,0.0,0.0,1.0,0.0,0.0,10.820397,4,75,88
7293,0.0,0.0,3.141593,-1550.775928,NaN,2096.483505,NaN,NaN,1.603794,0.0,1.0,0.0,0.0,NaN,0.0,0.0,0.0,-5.0,0.0,0.0,NaN,-2.022013,35.398605,1.0,NaN,0.0,-1.000000,1.000000,NaN,NaN,NaN,NaN,NaN,NaN,35.909604,35.398605,-1.0,NaN,0.0,0.0,35.906952,0.000000,0.0,1.603794,0.000000,0.0,1.000000,-1.00000,-0.435823,-0.899427,-0.032992,-169.050003,-62.550003,347.750031,-1.000000,0.964618,2196.098804,2090.440430,0.996608,2193.555176,1.869405,0.992283,1.839561,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,2607.709544,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.196099,NaN,10.0,NaN,0.0,0.0,NaN,-3020.834834,NaN,4050.227009,NaN,NaN,1.437684,0.0,0.0,0.0,-1.000000,0.0,0.0,NaN,NaN,0.0,-5.0,0.0,-2.210742,37.662312,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,39.912287,39.401275,-1.0,NaN,39.909016,1.437684,-0.591869,-0.795033,0.132719,-167.850006,-60.750000,348.049988,-2.171384,4227.464839,4121.800441,4226.144043,1.281252,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,1.0,NaN,-1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,0.0,0.0,5052.700458,NaN,0.0,0.0,1.0,0.0,0.0,4.227465,4,75,88
7294,0.0,0.0,NaN,0.000000,NaN,0.000000,NaN,NaN,-1.000000,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,-5.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,1.0,1.0,1.0,1.0,0.0,NaN,0.0,0.0,0.0,0.000000,NaN,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.000000,NaN,10.0,NaN,0.0,0.0,NaN,-329.335823,NaN,655.386215,NaN,NaN,-1.000000,0.0,0.0,0.0,-1.000000,0.0,0.0,NaN,NaN,0.0,-5.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.892180,833.733834,728.075574,827.011780,2.226736,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,-1.000000,1.0,NaN,-1.0,1.0,1.0,0.0,1.0,1.0,0.0,NaN,NaN,0.0,0.0,0.0,733.480180,NaN,0.0,0.0,1.0,0.0,0.0,0.833734,4,75,88

In [115]:
fin = uproot.open("root://fndcadoor.fnal.gov:/sbnd/persistent/users/mueller/MCP2025B/simulation/mc5e18/input000-reweighted.flat.caf.root:recTree")

In [13]:
fin.keys()

['rec.crt_hits..length',
 'rec.crt_hits.pe',
 'rec.crt_hits.plane',
 'rec.crt_hits.position.x',
 'rec.crt_hits.position.y',
 'rec.crt_hits.position.z',
 'rec.crt_hits.position_err.x',
 'rec.crt_hits.position_err.y',
 'rec.crt_hits.position_err.z',
 'rec.crt_hits.t0',
 'rec.crt_hits.t1',
 'rec.crt_hits.time',
 'rec.crt_spacepoints..length',
 'rec.crt_spacepoints.complete',
 'rec.crt_spacepoints.pe',
 'rec.crt_spacepoints.position.x',
 'rec.crt_spacepoints.position.y',
 'rec.crt_spacepoints.position.z',
 'rec.crt_spacepoints.position_err.x',
 'rec.crt_spacepoints.position_err.y',
 'rec.crt_spacepoints.position_err.z',
 'rec.crt_spacepoints.time',
 'rec.crt_spacepoints.time_err',
 'rec.crt_tracks..length',
 'rec.crt_tracks.hita.pe',
 'rec.crt_tracks.hita.plane',
 'rec.crt_tracks.hita.position.x',
 'rec.crt_tracks.hita.position.y',
 'rec.crt_tracks.hita.position.z',
 'rec.crt_tracks.hita.position_err.x',
 'rec.crt_tracks.hita.position_err.y',
 'rec.crt_tracks.hita.position_err.z',
 'rec.crt_tracks.hita.t0',
 'rec.crt_tracks.hita.t1',
 'rec.crt_tracks.hita.time',
 'rec.crt_tracks.hitb.pe',
 'rec.crt_tracks.hitb.plane',
 'rec.crt_tracks.hitb.position.x',
 'rec.crt_tracks.hitb.position.y',
 'rec.crt_tracks.hitb.position.z',
 'rec.crt_tracks.hitb.position_err.x',
 'rec.crt_tracks.hitb.position_err.y',
 'rec.crt_tracks.hitb.position_err.z',
 'rec.crt_tracks.hitb.t0',
 'rec.crt_tracks.hitb.t1',
 'rec.crt_tracks.hitb.time',
 'rec.crt_tracks.time',
 'rec.crtpmt_matches..length',
 'rec.crtpmt_matches.firstOpHitPeakTime',
 'rec.crtpmt_matches.firstOpHitStartTime',
 'rec.crtpmt_matches.flashClassification',
 'rec.crtpmt_matches.flashGateTime',
 'rec.crtpmt_matches.flashID',
 'rec.crtpmt_matches.flashInBeam',
 'rec.crtpmt_matches.flashInGate',
 'rec.crtpmt_matches.flashPE',
 'rec.crtpmt_matches.flashPosition.x',
 'rec.crtpmt_matches.flashPosition.y',
 'rec.crtpmt_matches.flashPosition.z',
 'rec.crtpmt_matches.flashTime_us',
 'rec.crtpmt_matches.flashYWidth',
 'rec.crtpmt_matches.flashZWidth',
 'rec.crtpmt_matches.matchedCRTHits..length',
 'rec.crtpmt_matches.matchedCRTHits..totarraysize',
 'rec.crtpmt_matches.matchedCRTHits.PMTTimeDiff',
 'rec.crtpmt_matches.matchedCRTHits.position.x',
 'rec.crtpmt_matches.matchedCRTHits.position.y',
 'rec.crtpmt_matches.matchedCRTHits.position.z',
 'rec.crtpmt_matches.matchedCRTHits.region',
 'rec.crtpmt_matches.matchedCRTHits.sys',
 'rec.crtpmt_matches.matchedCRTHits.time',
 'rec.crtpmt_matches.matchedCRTHits..idx',
 'rec.dlp..length',
 'rec.dlp.cathode_offset',
 'rec.dlp.depositions_sum',
 'rec.dlp.flash_hypo_pe',
 'rec.dlp.flash_ids..length',
 'rec.dlp.flash_ids..totarraysize',
 'rec.dlp.flash_ids',
 'rec.dlp.flash_ids..idx',
 'rec.dlp.flash_scores..length',
 'rec.dlp.flash_scores..totarraysize',
 'rec.dlp.flash_scores',
 'rec.dlp.flash_scores..idx',
 'rec.dlp.flash_times..length',
 'rec.dlp.flash_times..totarraysize',
 'rec.dlp.flash_times',
 'rec.dlp.flash_times..idx',
 'rec.dlp.flash_total_pe',
 'rec.dlp.flash_volume_ids..length',
 'rec.dlp.flash_volume_ids..totarraysize',
 'rec.dlp.flash_volume_ids',
 'rec.dlp.flash_volume_ids..idx',
 'rec.dlp.id',
 'rec.dlp.is_cathode_crosser',
 'rec.dlp.is_contained',
 'rec.dlp.is_fiducial',
 'rec.dlp.is_flash_matched',
 'rec.dlp.is_matched',
 'rec.dlp.is_time_contained',
 'rec.dlp.is_truth',
 'rec.dlp.match_ids..length',
 'rec.dlp.match_ids..totarraysize',
 'rec.dlp.match_ids',
 'rec.dlp.match_ids..idx',
 'rec.dlp.match_overlaps..length',
 'rec.dlp.match_overlaps..totarraysize',
 'rec.dlp.match_overlaps',
 'rec.dlp.match_overlaps..idx',
 'rec.dlp.module_ids..length',
 'rec.dlp.module_ids..totarraysize',
 'rec.dlp.module_ids',
 'rec.dlp.module_ids..idx',
 'rec.dlp.num_particles',
 'rec.dlp.num_primary_particles',
 'rec.dlp.particle_counts.0',
 'rec.dlp.particle_counts.1',
 'rec.dlp.particle_counts.2',
 'rec.dlp.particle_counts.3',
 'rec.dlp.particle_counts.4',
 'rec.dlp.particle_counts.5',
 'rec.dlp.particle_ids..length',
 'rec.dlp.particle_ids..totarraysize',
 'rec.dlp.particle_ids',
 'rec.dlp.particle_ids..idx',
 'rec.dlp.particles..length',
 'rec.dlp.particles..totarraysize',
 'rec.dlp.particles.axial_spread',
 'rec.dlp.particles.calo_ke',
 'rec.dlp.particles.cathode_offset',
 'rec.dlp.particles.chi2_per_pid.0',
 'rec.dlp.particles.chi2_per_pid.1',
 'rec.dlp.particles.chi2_per_pid.2',
 'rec.dlp.particles.chi2_per_pid.3',
 'rec.dlp.particles.chi2_per_pid.4',
 'rec.dlp.particles.chi2_per_pid.5',
 'rec.dlp.particles.chi2_pid',
 'rec.dlp.particles.csda_ke',
 'rec.dlp.particles.csda_ke_per_pid.0',
 'rec.dlp.particles.csda_ke_per_pid.1',
 'rec.dlp.particles.csda_ke_per_pid.2',
 'rec.dlp.particles.csda_ke_per_pid.3',
 'rec.dlp.particles.csda_ke_per_pid.4',
 'rec.dlp.particles.csda_ke_per_pid.5',
 'rec.dlp.particles.depositions_sum',
 'rec.dlp.particles.directional_spread',
 'rec.dlp.particles.end_dir.0',
 'rec.dlp.particles.end_dir.1',
 'rec.dlp.particles.end_dir.2',
 'rec.dlp.particles.end_point.0',
 'rec.dlp.particles.end_point.1',
 'rec.dlp.particles.end_point.2',
 'rec.dlp.particles.fragment_ids..length',
 'rec.dlp.particles.fragment_ids..totarraysize',
 'rec.dlp.particles.fragment_ids',
 'rec.dlp.particles.fragment_ids..idx',
 'rec.dlp.particles.id',
 'rec.dlp.particles.interaction_id',
 'rec.dlp.particles.is_cathode_crosser',
 'rec.dlp.particles.is_contained',
 'rec.dlp.particles.is_matched',
 'rec.dlp.particles.is_primary',
 'rec.dlp.particles.is_time_contained',
 'rec.dlp.particles.is_truth',
 'rec.dlp.particles.is_valid',
 'rec.dlp.particles.ke',
 'rec.dlp.particles.length',
 'rec.dlp.particles.mass',
 'rec.dlp.particles.match_ids..length',
 'rec.dlp.particles.match_ids..totarraysize',
 'rec.dlp.particles.match_ids',
 'rec.dlp.particles.match_ids..idx',
 'rec.dlp.particles.match_overlaps..length',
 'rec.dlp.particles.match_overlaps..totarraysize',
 'rec.dlp.particles.match_overlaps',
 'rec.dlp.particles.match_overlaps..idx',
 'rec.dlp.particles.mcs_ke',
 'rec.dlp.particles.mcs_ke_per_pid.0',
 'rec.dlp.particles.mcs_ke_per_pid.1',
 'rec.dlp.particles.mcs_ke_per_pid.2',
 'rec.dlp.particles.mcs_ke_per_pid.3',
 'rec.dlp.particles.mcs_ke_per_pid.4',
 'rec.dlp.particles.mcs_ke_per_pid.5',
 'rec.dlp.particles.module_ids..length',
 'rec.dlp.particles.module_ids..totarraysize',
 'rec.dlp.particles.module_ids',
 'rec.dlp.particles.module_ids..idx',
 'rec.dlp.particles.momentum.0',
 'rec.dlp.particles.momentum.1',
 'rec.dlp.particles.momentum.2',
 'rec.dlp.particles.num_fragments',
 'rec.dlp.particles.p',
 'rec.dlp.particles.pdg_code',
 'rec.dlp.particles.pid',
 'rec.dlp.particles.pid_scores.0',
 'rec.dlp.particles.pid_scores.1',
 'rec.dlp.particles.pid_scores.2',
 'rec.dlp.particles.pid_scores.3',
 'rec.dlp.particles.pid_scores.4',
 'rec.dlp.particles.pid_scores.5',
 'rec.dlp.particles.ppn_ids..length',
 'rec.dlp.particles.ppn_ids..totarraysize',
 'rec.dlp.particles.ppn_ids',
 'rec.dlp.particles.ppn_ids..idx',
 'rec.dlp.particles.primary_scores.0',
 'rec.dlp.particles.primary_scores.1',
 'rec.dlp.particles.shape',
 'rec.dlp.particles.size',
 'rec.dlp.particles.start_dedx',
 'rec.dlp.particles.start_dir.0',
 'rec.dlp.particles.start_dir.1',
 'rec.dlp.particles.start_dir.2',
 'rec.dlp.particles.start_point.0',
 'rec.dlp.particles.start_point.1',
 'rec.dlp.particles.start_point.2',
 'rec.dlp.particles.start_straightness',
 'rec.dlp.particles.units..length',
 'rec.dlp.particles.units..totarraysize',
 'rec.dlp.particles.units',
 'rec.dlp.particles.units..idx',
 'rec.dlp.particles.vertex_distance',
 'rec.dlp.particles..idx',
 'rec.dlp.primary_particle_counts.0',
 'rec.dlp.primary_particle_counts.1',
 'rec.dlp.primary_particle_counts.2',
 'rec.dlp.primary_particle_counts.3',
 'rec.dlp.primary_particle_counts.4',
 'rec.dlp.primary_particle_counts.5',
 'rec.dlp.primary_particle_ids..length',
 'rec.dlp.primary_particle_ids..totarraysize',
 'rec.dlp.primary_particle_ids',
 'rec.dlp.primary_particle_ids..idx',
 'rec.dlp.size',
 'rec.dlp.topology..length',
 'rec.dlp.topology..totarraysize',
 'rec.dlp.topology',
 'rec.dlp.topology..idx',
 'rec.dlp.units..length',
 'rec.dlp.units..totarraysize',
 'rec.dlp.units',
 'rec.dlp.units..idx',
 'rec.dlp.vertex.0',
 'rec.dlp.vertex.1',
 'rec.dlp.vertex.2',
 'rec.dlp_true..length',
 'rec.dlp_true.bjorken_x',
 'rec.dlp_true.cathode_offset',
 'rec.dlp_true.creation_process..length',
 'rec.dlp_true.creation_process..totarraysize',
 'rec.dlp_true.creation_process',
 'rec.dlp_true.creation_process..idx',
 'rec.dlp_true.current_type',
 'rec.dlp_true.depositions_adapt_q_sum',
 'rec.dlp_true.depositions_adapt_sum',
 'rec.dlp_true.depositions_g4_sum',
 'rec.dlp_true.depositions_q_sum',
 'rec.dlp_true.depositions_sum',
 'rec.dlp_true.distance_travel',
 'rec.dlp_true.energy_init',
 'rec.dlp_true.energy_transfer',
 'rec.dlp_true.flash_hypo_pe',
 'rec.dlp_true.flash_ids..length',
 'rec.dlp_true.flash_ids..totarraysize',
 'rec.dlp_true.flash_ids',
 'rec.dlp_true.flash_ids..idx',
 'rec.dlp_true.flash_scores..length',
 'rec.dlp_true.flash_scores..totarraysize',
 'rec.dlp_true.flash_scores',
 'rec.dlp_true.flash_scores..idx',
 'rec.dlp_true.flash_times..length',
 'rec.dlp_true.flash_times..totarraysize',
 'rec.dlp_true.flash_times',
 'rec.dlp_true.flash_times..idx',
 'rec.dlp_true.flash_total_pe',
 'rec.dlp_true.flash_volume_ids..length',
 'rec.dlp_true.flash_volume_ids..totarraysize',
 'rec.dlp_true.flash_volume_ids',
 'rec.dlp_true.flash_volume_ids..idx',
 'rec.dlp_true.hadronic_invariant_mass',
 'rec.dlp_true.id',
 'rec.dlp_true.inelasticity',
 'rec.dlp_true.interaction_id',
 'rec.dlp_true.interaction_mode',
 'rec.dlp_true.interaction_type',
 'rec.dlp_true.is_cathode_crosser',
 'rec.dlp_true.is_contained',
 'rec.dlp_true.is_fiducial',
 'rec.dlp_true.is_flash_matched',
 'rec.dlp_true.is_matched',
 'rec.dlp_true.is_time_contained',
 'rec.dlp_true.is_truth',
 'rec.dlp_true.lepton_p',
 'rec.dlp_true.lepton_pdg_code',
 'rec.dlp_true.lepton_track_id',
 'rec.dlp_true.match_ids..length',
 'rec.dlp_true.match_ids..totarraysize',
 'rec.dlp_true.match_ids',
 'rec.dlp_true.match_ids..idx',
 'rec.dlp_true.match_overlaps..length',
 'rec.dlp_true.match_overlaps..totarraysize',
 'rec.dlp_true.match_overlaps',
 'rec.dlp_true.match_overlaps..idx',
 'rec.dlp_true.mct_index',
 'rec.dlp_true.module_ids..length',
 'rec.dlp_true.module_ids..totarraysize',
 'rec.dlp_true.module_ids',
 'rec.dlp_true.module_ids..idx',
 'rec.dlp_true.momentum.0',
 'rec.dlp_true.momentum.1',
 'rec.dlp_true.momentum.2',
 'rec.dlp_true.momentum_transfer',
 'rec.dlp_true.momentum_transfer_mag',
 'rec.dlp_true.nu_id',
 'rec.dlp_true.nucleon',
 'rec.dlp_true.num_particles',
 'rec.dlp_true.num_primary_particles',
 'rec.dlp_true.orig_id',
 'rec.dlp_true.particle_counts.0',
 'rec.dlp_true.particle_counts.1',
 'rec.dlp_true.particle_counts.2',
 'rec.dlp_true.particle_counts.3',
 'rec.dlp_true.particle_counts.4',
 'rec.dlp_true.particle_counts.5',
 'rec.dlp_true.particle_ids..length',
 'rec.dlp_true.particle_ids..totarraysize',
 'rec.dlp_true.particle_ids',
 'rec.dlp_true.particle_ids..idx',
 'rec.dlp_true.particles..length',
 'rec.dlp_true.particles..totarraysize',
 'rec.dlp_true.particles.ancestor_creation_process..length',
 'rec.dlp_true.particles.ancestor_creation_process..totarraysize',
 'rec.dlp_true.particles.ancestor_creation_process',
 'rec.dlp_true.particles.ancestor_creation_process..idx',
 'rec.dlp_true.particles.ancestor_pdg_code',
 'rec.dlp_true.particles.ancestor_position.0',
 'rec.dlp_true.particles.ancestor_position.1',
 'rec.dlp_true.particles.ancestor_position.2',
 'rec.dlp_true.particles.ancestor_t',
 'rec.dlp_true.particles.ancestor_track_id',
 'rec.dlp_true.particles.calo_ke',
 'rec.dlp_true.particles.cathode_offset',
 'rec.dlp_true.particles.children_counts..length',
 'rec.dlp_true.particles.children_counts..totarraysize',
 'rec.dlp_true.particles.children_counts',
 'rec.dlp_true.particles.children_counts..idx',
 'rec.dlp_true.particles.children_id..length',
 'rec.dlp_true.particles.children_id..totarraysize',
 'rec.dlp_true.particles.children_id',
 'rec.dlp_true.particles.children_id..idx',
 'rec.dlp_true.particles.creation_process..length',
 'rec.dlp_true.particles.creation_process..totarraysize',
 'rec.dlp_true.particles.creation_process',
 'rec.dlp_true.particles.creation_process..idx',
 'rec.dlp_true.particles.csda_ke',
 'rec.dlp_true.particles.csda_ke_per_pid.0',
 'rec.dlp_true.particles.csda_ke_per_pid.1',
 'rec.dlp_true.particles.csda_ke_per_pid.2',
 'rec.dlp_true.particles.csda_ke_per_pid.3',
 'rec.dlp_true.particles.csda_ke_per_pid.4',
 'rec.dlp_true.particles.csda_ke_per_pid.5',
 'rec.dlp_true.particles.depositions_adapt_q_sum',
 'rec.dlp_true.particles.depositions_adapt_sum',
 'rec.dlp_true.particles.depositions_g4_sum',
 'rec.dlp_true.particles.depositions_q_sum',
 'rec.dlp_true.particles.depositions_sum',
 'rec.dlp_true.particles.distance_travel',
 'rec.dlp_true.particles.end_dir.0',
 'rec.dlp_true.particles.end_dir.1',
 'rec.dlp_true.particles.end_dir.2',
 'rec.dlp_true.particles.end_momentum.0',
 'rec.dlp_true.particles.end_momentum.1',
 'rec.dlp_true.particles.end_momentum.2',
 'rec.dlp_true.particles.end_p',
 'rec.dlp_true.particles.end_point.0',
 'rec.dlp_true.particles.end_point.1',
 'rec.dlp_true.particles.end_point.2',
 'rec.dlp_true.particles.end_position.0',
 'rec.dlp_true.particles.end_position.1',
 'rec.dlp_true.particles.end_position.2',
 'rec.dlp_true.particles.end_t',
 'rec.dlp_true.particles.energy_deposit',
 'rec.dlp_true.particles.energy_init',
 'rec.dlp_true.particles.first_step.0',
 'rec.dlp_true.particles.first_step.1',
 'rec.dlp_true.particles.first_step.2',
 'rec.dlp_true.particles.fragment_ids..length',
 'rec.dlp_true.particles.fragment_ids..totarraysize',
 'rec.dlp_true.particles.fragment_ids',
 'rec.dlp_true.particles.fragment_ids..idx',
 'rec.dlp_true.particles.group_id',
 'rec.dlp_true.particles.group_primary',
 'rec.dlp_true.particles.id',
 'rec.dlp_true.particles.interaction_id',
 'rec.dlp_true.particles.interaction_primary',
 'rec.dlp_true.particles.is_cathode_crosser',
 'rec.dlp_true.particles.is_contained',
 'rec.dlp_true.particles.is_matched',
 'rec.dlp_true.particles.is_primary',
 'rec.dlp_true.particles.is_time_contained',
 'rec.dlp_true.particles.is_truth',
 'rec.dlp_true.particles.is_valid',
 'rec.dlp_true.particles.ke',
 'rec.dlp_true.particles.last_step.0',
 'rec.dlp_true.particles.last_step.1',
 'rec.dlp_true.particles.last_step.2',
 'rec.dlp_true.particles.length',
 'rec.dlp_true.particles.mass',
 'rec.dlp_true.particles.match_ids..length',
 'rec.dlp_true.particles.match_ids..totarraysize',
 'rec.dlp_true.particles.match_ids',
 'rec.dlp_true.particles.match_ids..idx',
 'rec.dlp_true.particles.match_overlaps..length',
 'rec.dlp_true.particles.match_overlaps..totarraysize',
 'rec.dlp_true.particles.match_overlaps',
 'rec.dlp_true.particles.match_overlaps..idx',
 'rec.dlp_true.particles.mcs_ke',
 'rec.dlp_true.particles.mcs_ke_per_pid.0',
 'rec.dlp_true.particles.mcs_ke_per_pid.1',
 'rec.dlp_true.particles.mcs_ke_per_pid.2',
 'rec.dlp_true.particles.mcs_ke_per_pid.3',
 'rec.dlp_true.particles.mcs_ke_per_pid.4',
 'rec.dlp_true.particles.mcs_ke_per_pid.5',
 'rec.dlp_true.particles.mcst_index',
 'rec.dlp_true.particles.mct_index',
 'rec.dlp_true.particles.module_ids..length',
 'rec.dlp_true.particles.module_ids..totarraysize',
 'rec.dlp_true.particles.module_ids',
 'rec.dlp_true.particles.module_ids..idx',
 'rec.dlp_true.particles.momentum.0',
 'rec.dlp_true.particles.momentum.1',
 'rec.dlp_true.particles.momentum.2',
 'rec.dlp_true.particles.nu_id',
 'rec.dlp_true.particles.num_fragments',
 'rec.dlp_true.particles.num_voxels',
 'rec.dlp_true.particles.orig_children_id..length',
 'rec.dlp_true.particles.orig_children_id..totarraysize',
 'rec.dlp_true.particles.orig_children_id',
 'rec.dlp_true.particles.orig_children_id..idx',
 'rec.dlp_true.particles.orig_group_id',
 'rec.dlp_true.particles.orig_id',
 'rec.dlp_true.particles.orig_interaction_id',
 'rec.dlp_true.particles.orig_parent_id',
 'rec.dlp_true.particles.p',
 'rec.dlp_true.particles.parent_creation_process..length',
 'rec.dlp_true.particles.parent_creation_process..totarraysize',
 'rec.dlp_true.particles.parent_creation_process',
 'rec.dlp_true.particles.parent_creation_process..idx',
 'rec.dlp_true.particles.parent_id',
 'rec.dlp_true.particles.parent_pdg_code',
 'rec.dlp_true.particles.parent_position.0',
 'rec.dlp_true.particles.parent_position.1',
 'rec.dlp_true.particles.parent_position.2',
 'rec.dlp_true.particles.parent_t',
 'rec.dlp_true.particles.parent_track_id',
 'rec.dlp_true.particles.pdg_code',
 'rec.dlp_true.particles.pid',
 'rec.dlp_true.particles.position.0',
 'rec.dlp_true.particles.position.1',
 'rec.dlp_true.particles.position.2',
 'rec.dlp_true.particles.reco_end_dir.0',
 'rec.dlp_true.particles.reco_end_dir.1',
 'rec.dlp_true.particles.reco_end_dir.2',
 'rec.dlp_true.particles.reco_ke',
 'rec.dlp_true.particles.reco_length',
 'rec.dlp_true.particles.reco_momentum.0',
 'rec.dlp_true.particles.reco_momentum.1',
 'rec.dlp_true.particles.reco_momentum.2',
 'rec.dlp_true.particles.reco_start_dir.0',
 'rec.dlp_true.particles.reco_start_dir.1',
 'rec.dlp_true.particles.reco_start_dir.2',
 'rec.dlp_true.particles.shape',
 'rec.dlp_true.particles.size',
 'rec.dlp_true.particles.size_adapt',
 'rec.dlp_true.particles.size_g4',
 'rec.dlp_true.particles.start_dir.0',
 'rec.dlp_true.particles.start_dir.1',
 'rec.dlp_true.particles.start_dir.2',
 'rec.dlp_true.particles.start_point.0',
 'rec.dlp_true.particles.start_point.1',
 'rec.dlp_true.particles.start_point.2',
 'rec.dlp_true.particles.t',
 'rec.dlp_true.particles.track_id',
 'rec.dlp_true.particles.units..length',
 'rec.dlp_true.particles.units..totarraysize',
 'rec.dlp_true.particles.units',
 'rec.dlp_true.particles.units..idx',
 'rec.dlp_true.particles..idx',
 'rec.dlp_true.pdg_code',
 'rec.dlp_true.position.0',
 'rec.dlp_true.position.1',
 'rec.dlp_true.position.2',
 'rec.dlp_true.primary_particle_counts.0',
 'rec.dlp_true.primary_particle_counts.1',
 'rec.dlp_true.primary_particle_counts.2',
 'rec.dlp_true.primary_particle_counts.3',
 'rec.dlp_true.primary_particle_counts.4',
 'rec.dlp_true.primary_particle_counts.5',
 'rec.dlp_true.primary_particle_ids..length',
 'rec.dlp_true.primary_particle_ids..totarraysize',
 'rec.dlp_true.primary_particle_ids',
 'rec.dlp_true.primary_particle_ids..idx',
 'rec.dlp_true.quark',
 'rec.dlp_true.reco_vertex.0',
 'rec.dlp_true.reco_vertex.1',
 'rec.dlp_true.reco_vertex.2',
 'rec.dlp_true.size',
 'rec.dlp_true.size_adapt',
 'rec.dlp_true.size_g4',
 'rec.dlp_true.target',
 'rec.dlp_true.theta',
 'rec.dlp_true.topology..length',
 'rec.dlp_true.topology..totarraysize',
 'rec.dlp_true.topology',
 'rec.dlp_true.topology..idx',
 'rec.dlp_true.track_id',
 'rec.dlp_true.units..length',
 'rec.dlp_true.units..totarraysize',
 'rec.dlp_true.units',
 'rec.dlp_true.units..idx',
 'rec.dlp_true.vertex.0',
 'rec.dlp_true.vertex.1',
 'rec.dlp_true.vertex.2',
 'rec.fake_reco..length',
 'rec.fake_reco.filled',
 'rec.fake_reco.hadrons..length',
 'rec.fake_reco.hadrons..totarraysize',
 'rec.fake_reco.hadrons.contained',
 'rec.fake_reco.hadrons.costh',
 'rec.fake_reco.hadrons.ke',
 'rec.fake_reco.hadrons.len',
 'rec.fake_reco.hadrons.pid',
 'rec.fake_reco.hadrons..idx',
 'rec.fake_reco.lepton.contained',
 'rec.fake_reco.lepton.costh',
 'rec.fake_reco.lepton.ke',
 'rec.fake_reco.lepton.len',
 'rec.fake_reco.lepton.pid',
 'rec.fake_reco.nhad',
 'rec.fake_reco.nuE',
 'rec.fake_reco.vtx.x',
 'rec.fake_reco.vtx.y',
 'rec.fake_reco.vtx.z',
 'rec.fake_reco.wgt',
 'rec.hdr.bnbinfo..length',
 'rec.hdr.bnbinfo.BTJT2',
 'rec.hdr.bnbinfo.HP873',
 'rec.hdr.bnbinfo.HP875',
 'rec.hdr.bnbinfo.HPTG1',
 'rec.hdr.bnbinfo.HPTG2',
 'rec.hdr.bnbinfo.LM875A',
 'rec.hdr.bnbinfo.LM875B',
 'rec.hdr.bnbinfo.LM875C',
 'rec.hdr.bnbinfo.M875BB..length',
 'rec.hdr.bnbinfo.M875BB..totarraysize',
 'rec.hdr.bnbinfo.M875BB',
 'rec.hdr.bnbinfo.M875BB..idx',
 'rec.hdr.bnbinfo.M875BB_spill_time_diff',
 'rec.hdr.bnbinfo.M875HM',

In [116]:
arrays = fin.arrays(["rec.hdr.evt", "rec.hdr.run", "rec.dlp_true.particles.ke", \
                    "rec.dlp_true.particles.pdg_code", "rec.dlp_true.particles.is_primary", \
                    "rec.dlp_true.particles.pid", "rec.dlp_true.particles.is_valid", \
                    "rec.dlp_true.particles.is_contained", "rec.dlp_true.particles.is_matched", \
                    "rec.dlp_true.particles.match_overlaps", "rec.dlp_true.id"], \
        "(rec.hdr.run == 4) & (rec.hdr.evt == 88) & (rec.hdr.subrun == 75)", \
        library="ak")

In [36]:
arrays

In [103]:
# ak.max(arrays['rec.dlp_true.particles.ke'][abs(arrays['rec.dlp_true.particles.pdg_code']) == 13], axis=1)
arrays['rec.dlp_true.particles.ke'][(abs(arrays['rec.dlp_true.particles.pdg_code']) == 13) & (arrays['rec.dlp_true.particles.is_primary'] == True)]

muon_mask = (abs(arrays['rec.dlp_true.particles.pdg_code']) == 13) 
primary_mask = (arrays['rec.dlp_true.particles.is_primary'] == True)
electron_mask = (abs(arrays['rec.dlp_true.particles.pdg_code']) == 11)

total_particles = ak.count(arrays['rec.dlp_true.particles.ke'], axis=1)
total_muons = ak.count(arrays['rec.dlp_true.particles.ke'][muon_mask], axis=1)
primary_particles = ak.count(arrays['rec.dlp_true.particles.ke'][primary_mask], axis=1)
primary_muons = ak.count(arrays['rec.dlp_true.particles.ke'][muon_mask & primary_mask], axis=1)
total_electrons = ak.count(arrays['rec.dlp_true.particles.ke'][electron_mask], axis=1)
primary_electrons = ak.count(arrays['rec.dlp_true.particles.ke'][electron_mask & primary_mask], axis=1)

print(f"Total particles: {total_particles}")
print(f"Total muons: {total_muons}")
print(f"Primary particles: {primary_particles}")
print(f"Primary muons: {primary_muons}")
print(f"Total electrons: {total_electrons}")
print(f"Primary electrons: {primary_electrons}")

Total particles: [44]
Total muons: [12]
Primary particles: [14]
Primary muons: [12]
Total electrons: [31]
Primary electrons: [1]

In [104]:
ak.where((abs(arrays['rec.dlp_true.particles.pdg_code']) == 11) & (arrays['rec.dlp_true.particles.is_primary'] == True))

(<Array [0] type='1 * int64'>, <Array [0] type='1 * int64'>)

In [105]:
arrays['rec.dlp_true.particles.ke'][arrays['rec.dlp_true.particles.is_primary'] == True].to_list()

[[846.9428758010413,
  281.21294547112575,
  1792.3799529605703,
  728.0755741048146,
  40559.422251045915,
  6784.1842041569,
  41714.837066202905,
  3183.0886892797903,
  15751.461948761164,
  1812.8190860038826,
  1039.7338316419682,
  1987.5710658618684,
  10714.748641464237,
  4121.800440904377]]

In [125]:
primary_mask = arrays['rec.dlp_true.particles.is_primary'] == True
valid_mask = arrays['rec.dlp_true.particles.is_valid'] == True
# first_int, _ = ak.broadcast_arrays((arrays['rec.dlp_true.id'] == 0), valid_mask)

first_int = arrays['rec.dlp_true.id'] == 0

In [128]:
arrays['rec.dlp_true.particles.pdg_code'][0, :].to_list()

[11,
 2212,
 13,
 11,
 -13,
 13,
 -13,
 11,
 11,
 11,
 11,
 13,
 11,
 11,
 11,
 11,
 11,
 -11,
 11,
 11,
 11,
 11,
 11,
 11,
 11,
 13,
 11,
 -13,
 13,
 11,
 13,
 11,
 11,
 11,
 13,
 11,
 13,
 11,
 11,
 -13,
 11,
 11,
 11,
 11]

In [118]:
arrays['rec.dlp_true.id'].to_list()

[[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]]

In [109]:
arrays['rec.dlp_true.particles.ke'][mask].to_list()

[[846.9428758010413,
  281.21294547112575,
  1792.3799529605703,
  40559.422251045915,
  6784.1842041569,
  41714.837066202905,
  3183.0886892797903,
  15751.461948761164,
  1812.8190860038826,
  1039.7338316419682,
  1987.5710658618684,
  10714.748641464237,
  4121.800440904377]]

In [112]:
import uproot
from makedf.makedf import make_spine_int_df, make_spine_part_df
from makedf.branches import spinetpart_branches
from pyanalib.pandas_helpers import loadbranches, pad_column_name, rename_to_XYZ

RUN, SUBRUN, EVT = 4, 75, 88

CAF = "root://fndcadoor.fnal.gov:/sbnd/persistent/users/mueller/MCP2025B/simulation/mc5e18/input000-reweighted.flat.caf.root"

with uproot.open(CAF) as fin:
    slcdf        = make_spine_int_df(fin)
    spinetpart_df = loadbranches(fin["recTree"], spinetpart_branches)
    rename_to_XYZ(spinetpart_df, ["momentum", "end_point", "start_point", "start_dir", "end_dir", "vertex"])

# locate the entry via the df already loaded in the notebook
event_mask = (df['run'] == RUN) & (df['subrun'] == SUBRUN) & (df['evt'] == EVT)
row = df[event_mask]
print("Reco interactions for this event:")
print(row[['run','subrun','evt']].to_string())

entry    = row.index.get_level_values('entry')[0]
reco_int = row.index.get_level_values('rec.dlp..index')[0]

# which true interaction is matched to this reco slice?
true_int_col = pad_column_name(("rec.dlp_true..index",), slcdf)
matched_true_int = slcdf.loc[(entry, reco_int), true_int_col]
print(f"\nEntry={entry}, reco_int={reco_int} is matched to true_int={matched_true_int}")

# all muons in this event, showing which true interaction they belong to
pdg_col  = pad_column_name(('rec', 'dlp_true', 'particles', 'pdg_code'),   spinetpart_df)
ke_col   = pad_column_name(('rec', 'dlp_true', 'particles', 'ke'),         spinetpart_df)
prim_col = pad_column_name(('rec', 'dlp_true', 'particles', 'is_primary'), spinetpart_df)
valid_col= pad_column_name(('rec', 'dlp_true', 'particles', 'is_valid'),   spinetpart_df)

event_parts = spinetpart_df.loc[entry]
muons = event_parts[abs(event_parts[pdg_col]) == 13]
print(f"\nAll muons (index=[true_int, particle_idx]) — matched true_int is {matched_true_int}:")
print(muons[[ke_col, prim_col, valid_col]].to_string())

Reco interactions for this event:
                              run subrun evt




__ntuple entry rec.dlp..index
0        599   0                4     75  88
               1                4     75  88
               2                4     75  88
               3                4     75  88
               4                4     75  88
               5                4     75  88
               6                4     75  88
               7                4     75  88
               8                4     75  88
               9                4     75  88
               10               4     75  88
               11               4     75  88
               12               4     75  88

Entry=599, reco_int=0 is matched to true_int=nan

All muons (index=[true_int, particle_idx]) — matched true_int is nan:
                                                            rec
                                                       dlp_true
                                                      particles
                                                             ke is_primary is_valid

rec.dlp_true..index rec.dlp_true.particles..index
1                   0                               1792.379953          1        1
2                   0                                728.075574          1        0
3                   0                              40559.422251          1        1
4                   0                               6784.184204          1        1
5                   0                              41714.837066          1        1
6                   0                               3183.088689          1        1
7                   0                              15751.461949          1        1
8                   0                               1812.819086          1        1
9                   0                               1039.733832          1        1
10                  0                               1987.571066          1        1
11                  0                              10714.748641          1        1
12                  0                               4121.800441          1        1

In [113]:
RUN, SUBRUN, EVT = 4, 75, 88

# Get only the row(s) that actually passed the signal selection
sig_col1 = pad_column_name(('rec', 'dlp_true', 'true_signal1p'), df)
sig_col2 = pad_column_name(('rec', 'dlp_true', 'true_signalNp'), df)
event_mask = (df['run'] == RUN) & (df['subrun'] == SUBRUN) & (df['evt'] == EVT)
sig_mask   = event_mask & ((df[sig_col1] == True) | (df[sig_col2] == True))

row = df[sig_mask]
print("Signal reco interaction(s):")
print(row[['run','subrun','evt']].to_string())

entry    = row.index.get_level_values('entry')[0]
reco_int = row.index.get_level_values('rec.dlp..index')[0]

# which true interaction is matched to THIS reco slice?
true_int_col     = pad_column_name(("rec.dlp_true..index",), slcdf)
matched_true_int = slcdf.loc[(entry, reco_int), true_int_col]
print(f"\nEntry={entry}, reco_int={reco_int} → matched true_int={matched_true_int}")

# muons in this event — is any of them under matched_true_int?
event_parts = spinetpart_df.loc[entry]
muons = event_parts[abs(event_parts[pdg_col]) == 13]
print(f"\nAll muons (matched_true_int={matched_true_int}):")
print(muons[[ke_col, prim_col, valid_col]].to_string())

Signal reco interaction(s):
                              run subrun evt




__ntuple entry rec.dlp..index
0        599   1                4     75  88

Entry=599, reco_int=1 → matched true_int=0.0

All muons (matched_true_int=0.0):
                                                            rec
                                                       dlp_true
                                                      particles
                                                             ke is_primary is_valid

rec.dlp_true..index rec.dlp_true.particles..index
1                   0                               1792.379953          1        1
2                   0                                728.075574          1        0
3                   0                              40559.422251          1        1
4                   0                               6784.184204          1        1
5                   0                              41714.837066          1        1
6                   0                               3183.088689          1        1
7                   0                              15751.461949          1        1
8                   0                               1812.819086          1        1
9                   0                               1039.733832          1        1
10                  0                               1987.571066          1        1
11                  0                              10714.748641          1        1
12                  0                               4121.800441          1        1

In [26]:
# count each category in medulla and cafpyana
categories = ['true_signal1p', 'true_signalNp', 'bkgd_oofv', 'bkgd_oops', \
    'bkgd_pi', 'bkgd_mu', 'bkgd_photon', 'bkgd_nueOther', 'bkgd_numu', 'bkgd_nc', 'bkgd_other']

for i in range(len(categories)):
    index = i
    if i==0: index=1
    elif i==1: index=0
    signal_mask = (df_medulla['true_category'] == index).sum()
    print(f"Medulla: {categories[i]}: {signal_mask}")

print("Medulla: Total: ", len(df_medulla), " matched interactions: ", (df_medulla['true_category'].count()))
print('-----------------------')

for cat in categories:
    signal_mask = (df.rec.dlp_true[cat] == True).sum()
    print(f"Cafpyana: {cat}: {signal_mask}")

print("Cafpyana: Total: ", (df.rec.dlp_true[categories].sum(axis=1) > 0).sum(), " matched interactions: ", df.rec.dlp_true.is_fiducial.notnull().sum())

Medulla: true_signal1p: 9
Medulla: true_signalNp: 2
Medulla: bkgd_oofv: 6
Medulla: bkgd_oops: 12
Medulla: bkgd_pi: 5
Medulla: bkgd_mu: 0
Medulla: bkgd_photon: 1
Medulla: bkgd_nueOther: 22
Medulla: bkgd_numu: 8666
Medulla: bkgd_nc: 2288
Medulla: bkgd_other: 82493
Medulla: Total:  106786  matched interactions:  93504
-----------------------
Cafpyana: true_signal1p: 8
Cafpyana: true_signalNp: 2
Cafpyana: bkgd_oofv: 7
Cafpyana: bkgd_oops: 12
Cafpyana: bkgd_pi: 5
Cafpyana: bkgd_mu: 0
Cafpyana: bkgd_photon: 1
Cafpyana: bkgd_nueOther: 22
Cafpyana: bkgd_numu: 8666
Cafpyana: bkgd_nc: 2288
Cafpyana: bkgd_other: 95775
Cafpyana: Total:  106786  matched interactions:  93504